### PR TITLE
provider - Wrap errors

### PR DESCRIPTION
**Pull request by bbickerton**
#### Description:

Wrap provider errors with the errors package.
#### Issues affected:

Related #308

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/327)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[provider/config.go, line 152 [r1]](https://reviewable.io:443/reviews/cerana/cerana/327#-KPEJAW1vCGi3XeBX14N:-KPEJAW1vCGi3XeBX14O:b96efxh) ([raw file](https://github.com/cerana/cerana/blob/a60b1a7539a0868ae14660c593dd4ab5326ad192/provider/config.go#L152)):_

> ``` Go
>   coordinatorURL := c.viper.GetString("coordinator_url")
>   if _, err := url.ParseRequestURI(coordinatorURL); err != nil {
>       return errors.Wrapv(err, map[string]interface{}{"coordinatorURL": coordinatorURL}, "failed to parse coordinatorURL")
> ```

all the other errors are with `_`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/327)_

**Comment by mmlb** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[providers/clusterconf/bundle.go, line 322 [r2]](https://reviewable.io:443/reviews/cerana/cerana/327#-KPSdJdLnOX5oSp53MyV:-KPSdJdMEeRXKmFrtudK:b-b0ebmu) ([raw file](https://github.com/cerana/cerana/blob/281e5e6239716ced0dbfc5ae8ff0436a96efcb69/providers/clusterconf/bundle.go#L322)):_

> ``` Go
>   bundle, err := c.getBundle(args.ID)
>   if err != nil {
>       if strings.Contains(err.Error(), "bundle config not found") {
> ```

I wonder if it woukd make sense to have errors have a `NotFound()` function.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/327)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[provider/config.go, line 152 [r1]](https://reviewable.io:443/reviews/cerana/cerana/327#-KPEJAW1vCGi3XeBX14N:-KPT-mzWMGvOLDGwTvW8:b-v30th5) ([raw file](https://github.com/cerana/cerana/blob/a60b1a7539a0868ae14660c593dd4ab5326ad192/provider/config.go#L152)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> all the other errors are with `_`
> </details>
> If you're referring to `c.CoordinatorURL()`, then yes, that's fine. We're checking the error here in `Validate` so that the former doesn't have to worry.

---

_[providers/clusterconf/bundle.go, line 322 [r2]](https://reviewable.io:443/reviews/cerana/cerana/327#-KPSdJdLnOX5oSp53MyV:-KPT03dCzoPIuJFa80lj:b-v161s) ([raw file](https://github.com/cerana/cerana/blob/281e5e6239716ced0dbfc5ae8ff0436a96efcb69/providers/clusterconf/bundle.go#L322)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> I wonder if it woukd make sense to have errors have a `NotFound()` function.
> </details>
> Could be an interesting addition to the `errors` package. A `NotFound()` and a `Temporary()`. I'll make a card to revisit.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/327)_

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[provider/config.go, line 152 [r1]](https://reviewable.io:443/reviews/cerana/cerana/327#-KPEJAW1vCGi3XeBX14N:-KPT2NXFHlB6GghY9uzl:b2yzk7c) ([raw file](https://github.com/cerana/cerana/blob/a60b1a7539a0868ae14660c593dd4ab5326ad192/provider/config.go#L152)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> If you're referring to `c.CoordinatorURL()`, then yes, that's fine. We're checking the error here in `Validate` so that the former doesn't have to worry.
> </details>
> No I'm not worried about checking, just trying to have consistent naming/messages.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/327)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[provider/config.go, line 152 [r1]](https://reviewable.io:443/reviews/cerana/cerana/327#-KPEJAW1vCGi3XeBX14N:-KPT5NebFow5Cf0VOrsz:b-9034mx) ([raw file](https://github.com/cerana/cerana/blob/a60b1a7539a0868ae14660c593dd4ab5326ad192/provider/config.go#L152)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> No I'm not worried about checking, just trying to have consistent naming/messages.
> </details>
> Sorted out the confusion on irc. This comment was referring to casing, snake_case vs camelCase, where as I thought it was talking about the go black hole variable `_` throwing away errors. Consistency will be handled in #149 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/327)_

**Pull request merged**
