### PR TITLE
basic cluster bootstrap platform downloading

### LINKED ISSUE #209: Get Boot Media from boot server to put in ZFS Pool

### PR DESCRIPTION
**Pull request by nshalman**
#### Description:

To be demo-ready we need some way of getting the platform image onto the PXE booted nodes.
This works for now.
Resolves #209

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/288)

### CODE REVIEW

**Comment by nshalman** [comment]
Depends on bootserver landing. Tested to work on the current version of the bootserver branch.

**Comment by mmlb** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[boot/scripts/copy-platform.sh, line 20 [r2]](https://reviewable.io:443/reviews/cerana/cerana/288#-KNIQ5Jq_n7r1E7p6mPE:-KNIQ5Jq_n7r1E7p6mPF:1531275964) ([raw file](https://github.com/cerana/cerana/blob/9709e62641a5c0b90e9b5ce9790ad913d01cfbcf/boot/scripts/copy-platform.sh#L20)):_

> ``` Shell
>     rm -f /data/platform/current \
>         && ln -s "${DESTINATION#/data/platform/}" /data/platform/current
>     return $?
> ```

`ln -sf`?
`return $?` is superfluous

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/288)_

**Comment by nshalman** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[boot/scripts/copy-platform.sh, line 20 [r2]](https://reviewable.io:443/reviews/cerana/cerana/288#-KNIQ5Jq_n7r1E7p6mPE:-KNIXh1rsbGJk8FgZDZ2:931565276) ([raw file](https://github.com/cerana/cerana/blob/9709e62641a5c0b90e9b5ce9790ad913d01cfbcf/boot/scripts/copy-platform.sh#L20)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> `ln -sf`?
> `return $?` is superfluous
> </details>
> removed the extraneous `return $?`
> `ln -sf` has bitten me in the past when assumptions proved incorrect, thus the explicit remove and create.
> e.g. if someone created a directory named current rather than it being a symlink as expected.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/288)_

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/288)_

**Pull request merged**
