### PR TITLE
Add LoadConfig to clusterconf.Config

### LINKED ISSUE #239: Fix Providers' Configs
#### Issue Description

I had assumed that `c.LoadConfig` would be calling the embedded `c.Config.LoadConfig` with `c` as the target. But it was actually using `c.Config` as the target, which meant that the subsequent call to `Validate` was also just on the embedded part. Update all provider implementations to have a `LoadConfig()` method that calls the embedded `LoadConfig()` and the parent `validate`. e.g.

```
func (c *Config) LoadConfig() error {
       if err := c.Config.LoadConfig(); err != nil {
               return err
       }
       return c.Validate()
}
```
#### Acceptance Criteria (how do we know when this is done?)

Specific configuration is loaded and validated in addition to the base provider config.

### PR DESCRIPTION
**Pull request by bbickerton**
#### Description:

Correct the config loading of clusterconf
#### Issues affected:

Resolves #239

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/242)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/clusterconf/config.go, line 80 [r1]](https://reviewable.io:443/reviews/cerana/cerana/242#-KKyMKALjFmP9CjwxPtN:-KKyMKALjFmP9CjwxPtO:671586311) ([raw file](https://github.com/cerana/cerana/blob/70ac37b50ea19b5bf56c306a87033e24ca0786e9/providers/clusterconf/config.go#L80)):_

> ``` Go
> 
> // LoadConfig loads and validates the ClusterConf provider config.
> func (c *Config) LoadConfig() error {
> ```

hmm can we add tests to verify this is working?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/242)_

**Comment by mmlb** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/242)_

**Comment by bbickerton** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/clusterconf/config.go, line 80 [r1]](https://reviewable.io:443/reviews/cerana/cerana/242#-KKyMKALjFmP9CjwxPtN:-KKzI58BkBQCG_8Nswjd:-499146009) ([raw file](https://github.com/cerana/cerana/blob/70ac37b50ea19b5bf56c306a87033e24ca0786e9/providers/clusterconf/config.go#L80)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> hmm can we add tests to verify this is working?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/242)_

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[providers/clusterconf/config_test.go, line 66 [r2]](https://reviewable.io:443/reviews/cerana/cerana/242#-KL1BmJJUQ6oUIsN91dW:-KL1BmJJUQ6oUIsN91dX:-1038312768) ([raw file](https://github.com/cerana/cerana/blob/e18e5df180b4e4956089a8f104e8789db358f234/providers/clusterconf/config_test.go#L66)):_

> ``` Go
> }
> 
> func (s *clusterConf) TestLoadConfig() {
> ```

This test isn't doing what you think it is. I tried it on my branch pre-fix and the test passes.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/242)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[providers/clusterconf/config_test.go, line 66 [r2]](https://reviewable.io:443/reviews/cerana/cerana/242#-KL1BmJJUQ6oUIsN91dW:-KL1sCC_aYQjq1MkVr8L:1025078820) ([raw file](https://github.com/cerana/cerana/blob/e18e5df180b4e4956089a8f104e8789db358f234/providers/clusterconf/config_test.go#L66)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> This test isn't doing what you think it is. I tried it on my branch pre-fix and the test passes.
> </details>
> Ah, i think I know why. Looking over this again, there were actually two problems. One was that `LoadConfig` needed to be created in order to have validation done on the `clusterconf` specific flags. The other was fixing the cli flags which were mismatched `-` vs `_` separators, which prevented the values from making it through at all.  Since the tests had to add the flags that were placed in `main.go`, they added them correctly named, so just copying the test into the pre-fix branch would pass.

There's open issues both for normalizing the cli/viper/configfile parameters and for adding provider specific flags in the `NewConfig` so that those can be tested better with the rest of Config's methods.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/242)_

**Pull request merged**
