### PR TITLE
Add kv provider

### LINKED ISSUE #93: add consul implementation of pkg/kv/kv and switch to it
<a href="https://github.com/mmlb"></img></a> **Issue by [mmlb](https://github.com/mmlb)**
_Tue Mar 22 20:32:20 2016_
_Originally opened as https://github.com/mistifyio/lochness/issues/133_

---
# Description

Bring in pkg/kv from mistifyio/lochness into cerana
# Related Issues
#122 - abstract kv use into a package

### LINKED ISSUE #123: Layer 2 KV provider
## Issue Description

Implement Layer 2 kv provider.
## Acceptance Criteria (How do we know when this is done?)

Based on 04/13/2016 architecture discussion, the following tasks make up this card:
- [x] Set
- [x] Update
- [x] Delete
- [x] Remove
- [x] Watch
- [x] Lock
- [x] Ephemeral

### PR DESCRIPTION
**Pull request by mmlb**
#### Issues affected

Resolves #123
Resolves #93 also

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/192)

### CODE REVIEW

**Comment by bbickerton** [comment]
Reviewed 33 of 33 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[providers/kv/basic.go, line 55 [r1]](https://reviewable.io:443/reviews/cerana/cerana/192#-KJ764IaRf_oj2MoZIoj:-KJ764Ib4WVGpiKbLkoW:1408013738) ([raw file](https://github.com/cerana/cerana/blob/94b647188918e4df1696f2b1fab2d8dc8de63785/providers/kv/basic.go#L55)):_

> ``` Go
>   }
> 
>   return kvp.Data, nil, nil
> ```

We want to be returning the `kvp` so that we can keep track of the index for later modifications. Also to be in line with what `getAll` returns.

---

_[providers/kv/basic_test.go, line 89 [r1]](https://reviewable.io:443/reviews/cerana/cerana/192#-KJ77DW66I4BktF5Sxej:-KJ77DW66I4BktF5Sxek:-665851689) ([raw file](https://github.com/cerana/cerana/blob/94b647188918e4df1696f2b1fab2d8dc8de63785/providers/kv/basic_test.go#L89)):_

> ``` Go
>       }
> 
>       result, ok := res.([]byte)
> ```

See comment on the `get` handler

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/192)_

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[providers/kv/basic.go, line 55 [r1]](https://reviewable.io:443/reviews/cerana/cerana/192#-KJ764IaRf_oj2MoZIoj:-KJ7FvuLd-77zz3-QSDr:2144658136) ([raw file](https://github.com/cerana/cerana/blob/94b647188918e4df1696f2b1fab2d8dc8de63785/providers/kv/basic.go#L55)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> We want to be returning the `kvp` so that we can keep track of the index for later modifications. Also to be in line with what `getAll` returns.
> </details>
> woops, good call

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/192)_

**Comment by mmlb** [comment]
Review status: 31 of 33 files reviewed at latest revision, 2 unresolved discussions.

---

_[providers/kv/basic.go, line 55 [r1]](https://reviewable.io:443/reviews/cerana/cerana/192#-KJ764IaRf_oj2MoZIoj:-KJ7ctAxgTcAiIhCjCGT:-499146009) ([raw file](https://github.com/cerana/cerana/blob/94b647188918e4df1696f2b1fab2d8dc8de63785/providers/kv/basic.go#L55)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> woops, good call
> </details>
> Done.

---

_[providers/kv/basic_test.go, line 89 [r1]](https://reviewable.io:443/reviews/cerana/cerana/192#-KJ77DW66I4BktF5Sxej:-KJ7cu1rNgurc8bisT_E:-499146009) ([raw file](https://github.com/cerana/cerana/blob/94b647188918e4df1696f2b1fab2d8dc8de63785/providers/kv/basic_test.go#L89)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> See comment on the `get` handler
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/192)_

**Comment by bbickerton** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/192)_

**Comment by mmlb** [comment]
@tauzero PTAL

<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> #### Add kv provider
> 
> #### Issues affected
> 
> Resolves #123
> 
> </details>

---

Review status: 32 of 33 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/192#-:-KJ7yISQAmgkhOqJO5Ob:-1163627430)_

**Comment by bbickerton** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/192)_

**Pull request merged**
