### PR TITLE
rename management NIC to mgmt0

### PR DESCRIPTION
**Pull request by nshalman**
#### Description:

Give the management interface a predictable name to make it easier for the boot server to find it.

Tested to work.

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/277)

### CODE REVIEW

**Comment by nshalman** [comment]
Fails lint... don't merge yet.

**Comment by mmlb** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[boot/scripts/net-init.sh, line 116 [r2]](https://reviewable.io:443/reviews/cerana/cerana/277#-KM_vgkM8AXr_sF-wc5i:-KM_vgkM8AXr_sF-wc5j:1293700868) ([raw file](https://github.com/cerana/cerana/blob/2a67fb30fcb675636852be69b9c1a21372d75ee6/boot/scripts/net-init.sh#L116)):_

> ``` Shell
>     lshw | grep -iq joyent \
>         && echo -e "\n[DHCP]\nClientIdentifier=mac\n" >>/data/config/network/mgmt.network
>     ip link set "${MAC_TO_IFACE[${CERANA_MGMT_MAC}]}" name mgmt0
> ```

https://wiki.archlinux.org/index.php/systemd-networkd#Renaming_an_interface is a better solution no?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/277)_

**Comment by nshalman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[boot/scripts/net-init.sh, line 116 [r2]](https://reviewable.io:443/reviews/cerana/cerana/277#-KM_vgkM8AXr_sF-wc5i:-KMaBHG7mhbeSh20aSWZ:-1518617212) ([raw file](https://github.com/cerana/cerana/blob/2a67fb30fcb675636852be69b9c1a21372d75ee6/boot/scripts/net-init.sh#L116)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> https://wiki.archlinux.org/index.php/systemd-networkd#Renaming_an_interface is a better solution no?
> </details>
> That doesn't appear to work when I try it.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/277)_

**Comment by nshalman** [comment]
In my testing, creating a mgmt.link file in the network directory doesn't work.
I'm going to roll back that test commit.

**Comment by nshalman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[boot/scripts/net-init.sh, line 116 [r2]](https://reviewable.io:443/reviews/cerana/cerana/277#-KM_vgkM8AXr_sF-wc5i:-KMec7B39-sF1tfrPCsK:-702086612) ([raw file](https://github.com/cerana/cerana/blob/2a67fb30fcb675636852be69b9c1a21372d75ee6/boot/scripts/net-init.sh#L116)):_
<details><summary>

<i>Previously, nshalman (Nahum Shalman) wrote…</i></summary>



> That doesn't appear to work when I try it.
> </details>
> What was suggested doesn't work, so I'm sticking with what does.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/277)_

**Comment by nshalman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[boot/scripts/net-init.sh, line 116 [r2]](https://reviewable.io:443/reviews/cerana/cerana/277#-KM_vgkM8AXr_sF-wc5i:-KMecDrD7aoJs4AlAx3G:-499146009) ([raw file](https://github.com/cerana/cerana/blob/2a67fb30fcb675636852be69b9c1a21372d75ee6/boot/scripts/net-init.sh#L116)):_
<details><summary>

<i>Previously, nshalman (Nahum Shalman) wrote…</i></summary>



> What was suggested doesn't work, so I'm sticking with what does.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/277)_

**Comment by mmlb** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_[boot/scripts/net-init.sh, line 116 [r2]](https://reviewable.io:443/reviews/cerana/cerana/277#-KM_vgkM8AXr_sF-wc5i:-KMetoU2iw_yHkA5ZlAb:1221249294) ([raw file](https://github.com/cerana/cerana/blob/2a67fb30fcb675636852be69b9c1a21372d75ee6/boot/scripts/net-init.sh#L116)):_
<details><summary>

<i>Previously, nshalman (Nahum Shalman) wrote…</i></summary>



> Done.
> </details>
> I suspect it didn't work because of `Note: The default link file /usr/lib/systemd/network/99-default.link is shipped by the system. Any user-supplied .link should have a lexically earlier file name to be considered at all. For example, name the file 10-ethusb0.link  and not ethusb0.link.` I Just tried both `usbeth0.link` and `10-usbeth0.link` on a usb device and the former did not work for me.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/277)_

**Comment by nshalman** [comment]
Testing now.

**Comment by nshalman** [comment]
Still not working with filename of `10-mgmt.link`
Doesn't even work if I unload the kernel module for the network device and then reload it.
For the second time I'm declaring defeat on using the .link unit file and going back to my original working code.

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/277)_

**Comment by joshie** [comment]
LGTM as long as we open an issue to revisit why naming it in systemd-networking doesn't work

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/277#-:-KMj9khnBcrACTasguwK:-512814075)_

**Comment by joshie** [comment]
:lgtm:

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/277#-:-KMj9yEijLmZRiox3dmz:1417088721)_

**Comment by mmlb** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/277#-:-KMjEVuAK9C4Maemm1Ox:1417088721)_

**Pull request merged**
