### PR TITLE
256 data trade

### LINKED ISSUE #256: Data Trade Provider
#### Issue Description

Create a layer 2 provider for import and export of data. Currently all we want is dataset ingestion. 
- Use the `acomm.Request.StreamURL` for the location of where to pull data from. Provide configuration information.
- Generate a unique identifier for the dataset when naming the dataset on the zpool. 
- Import the dataset to one node via the node's `zfs-provider`
- After ingestion is complete and validated, then create the dataset config entry via the `clusterconf-provider`.  Include the dataset checksum in the dataset config in entry.

Replication will be handled by the cluster tick process.

### PR DESCRIPTION
**Pull request by bbickerton**
#### Description:

Provider for importing datasets (in the future it will have export and also handle other information)
#### Issues affected:

Resolves #256

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/281)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 5 of 5 files at r5, 4 of 4 files at r6, 1 of 1 files at r7, 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[providers/datatrade/dataset.go, line 18 [r5]](https://reviewable.io:443/reviews/cerana/cerana/281#-KN2cpvE4glK4jicx6z8:-KN2cpvE4glK4jicx6z9:678089183) ([raw file](https://github.com/cerana/cerana/blob/3f78d03550e20ecafcfad3e35c1ff8376c5410e9/providers/datatrade/dataset.go#L18)):_

> ``` Go
> type DatasetImportArgs struct {
>   NFS        bool `json:"nfs"`
>   Quota      int  `json:"quota"`
> ```

uint

---

_[providers/datatrade/dataset.go, line 20 [r5]](https://reviewable.io:443/reviews/cerana/cerana/281#-KN2co5mg3EbC2bMb-Jk:-KN2co5mg3EbC2bMb-Jl:-469765787) ([raw file](https://github.com/cerana/cerana/blob/3f78d03550e20ecafcfad3e35c1ff8376c5410e9/providers/datatrade/dataset.go#L20)):_

> ``` Go
>   Quota      int  `json:"quota"`
>   ReadOnly   bool `json:"readOnly"`
>   Redundancy int  `json:"redundancy"`
> ```

ditto

---

_[providers/datatrade/dataset.go, line 91 [r5]](https://reviewable.io:443/reviews/cerana/cerana/281#-KN2eZT2i1zuyozN92pr:-KN2eZT3MajYNeWjJcLj:-2125335647) ([raw file](https://github.com/cerana/cerana/blob/3f78d03550e20ecafcfad3e35c1ff8376c5410e9/providers/datatrade/dataset.go#L91)):_

> ``` Go
>       },
>   }
>   u, err := url.Parse(fmt.Sprintf("http://%s:%d", nodeID, p.config.NodeCoordinatorPort()))
> ```

NodeCoordinatorPort is never allowed to change, so that nodeID's NCP may not be the same as this one's? Probably not ever going to happen, but am curious.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/281)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[providers/datatrade/dataset.go, line 91 [r5]](https://reviewable.io:443/reviews/cerana/cerana/281#-KN2eZT2i1zuyozN92pr:-KN2p_dmleaEFAgxdLO7:1375897607) ([raw file](https://github.com/cerana/cerana/blob/3f78d03550e20ecafcfad3e35c1ff8376c5410e9/providers/datatrade/dataset.go#L91)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> NodeCoordinatorPort is never allowed to change, so that nodeID's NCP may not be the same as this one's? Probably not ever going to happen, but am curious.
> </details>
> Since the coordinator's address is configurable, i wanted this to be configurable. There is an assumption that the layer1 coordinator port will be the same across the cluster.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/281)_

**Comment by bbickerton** [comment]
Review status: 16 of 23 files reviewed at latest revision, 3 unresolved discussions.

---

_[providers/datatrade/dataset.go, line 18 [r5]](https://reviewable.io:443/reviews/cerana/cerana/281#-KN2cpvE4glK4jicx6z8:-KN3vZ6m2bg4Pv8A63UP:-1356960278) ([raw file](https://github.com/cerana/cerana/blob/3f78d03550e20ecafcfad3e35c1ff8376c5410e9/providers/datatrade/dataset.go#L18)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> uint
> </details>
> Done, and updated clusterconf accordingly.

---

_[providers/datatrade/dataset.go, line 20 [r5]](https://reviewable.io:443/reviews/cerana/cerana/281#-KN2co5mg3EbC2bMb-Jk:-KN3vZQqfbrk_fIL7g8o:-499146009) ([raw file](https://github.com/cerana/cerana/blob/3f78d03550e20ecafcfad3e35c1ff8376c5410e9/providers/datatrade/dataset.go#L20)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> ditto
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/281)_

**Comment by mmlb** [comment]
Reviewed 7 of 7 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/281)_

**Pull request merged**
