### PR TITLE
Demotick

### LINKED ISSUE #298: Demotick
#### Issue Description

Create a demo tick process to clone datasets and services across all nodes in the cluster. It will be run by hand

### PR DESCRIPTION
**Pull request by bbickerton**
#### Description:

Manually run command to replicate datasets and run all nodes on all nodes in a cluster. Intended for the demo of cerana and to be replaced by the full cluster tick at a later date.
#### Issues affected:

Resolves #298

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/299)

### CODE REVIEW

**Comment by mmlb** [comment]
This pr should be split into 2. The clusterconf part goes into main, and the demo tick should just go into a (new/temp) demo branch. No point adding to history if we aren't going to keep it.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/clusterconf/service.go, line 30 [r1]](https://reviewable.io:443/reviews/cerana/cerana/299#-KNbUVbfCFb7Lt-9wLaL:-KNbUVbfCFb7Lt-9wLaM:643356120) ([raw file](https://github.com/cerana/cerana/blob/c0eff8099f6f351feebea363653c5fede88b2469/providers/clusterconf/service.go#L30)):_

> ``` Go
>   Limits       ResourceLimits         `json:"limits"`
>   Env          map[string]string      `json:"env"`
>   Exec         []string               `json:"exec"`
> ```

this is named`cmd` in the arch doc, we need to keep in sync.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/299#-:-KNbUcJdQBXBZbUMEI0H:1113359583)_

**Comment by bbickerton** [comment]
Review status: 1 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/clusterconf/service.go, line 30 [r1]](https://reviewable.io:443/reviews/cerana/cerana/299#-KNbUVbfCFb7Lt-9wLaL:-KNbsihBHjmZ4oMyOXND:-499146009) ([raw file](https://github.com/cerana/cerana/blob/c0eff8099f6f351feebea363653c5fede88b2469/providers/clusterconf/service.go#L30)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> this is named`cmd` in the arch doc, we need to keep in sync.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/299)_

**Comment by mmlb** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/299)_

**Comment by bbickerton** [comment]
Closing PR. The conf changes were moved to #304. The demotick isn't going to go to master since it is temporary.

**Pull request closed without merging**
