### PR TITLE
Service provider

### LINKED ISSUE #166: Service Provider (systemd abstraction layer)
## Issue Description

Create a service provider layer that interacts with systemd for cerana system providers.
## Acceptance Criteria (How do we know when this is done?)

Initial implementation of the service provider layer.

### PR DESCRIPTION
**Pull request by bbickerton**
#### Description:

Service provider for managing services. It is a layer of abstraction above the systemd provider.

Note: There will be some tweaks around the uid/gid and Exec once the `daisy` binary is ready and can be used by this.
#### Issues affected:

Resolves #166

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/252)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r1, 7 of 7 files at r2, 15 of 15 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[providers/systemd/get.go, line 85 [r1]](https://reviewable.io:443/reviews/cerana/cerana/252#-KLwM_IxUQT0VNoEmj6o:-KLwM_IxUQT0VNoEmj6p:343803714) ([raw file](https://github.com/cerana/cerana/blob/2ad4e0fe817c8366f47aeb87834e6766e4759250/providers/systemd/get.go#L85)):_

> ``` Go
> 
>   if unitStatus.ActiveState == "active" {
>       activeEnter := time.Unix(int64(unitStatus.UnitProperties["ActiveEnterTimestamp"].(uint64))/int64(time.Second/time.Microsecond), 0)
> ```

What's the deal with this? What time unit does `UnitProperties` return? Also you can extract the int64 casts into just casting the result of the div.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/252)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[providers/systemd/get.go, line 85 [r1]](https://reviewable.io:443/reviews/cerana/cerana/252#-KLwM_IxUQT0VNoEmj6o:-KLwne1zBVYoyL4t0Yq6:-939568496) ([raw file](https://github.com/cerana/cerana/blob/2ad4e0fe817c8366f47aeb87834e6766e4759250/providers/systemd/get.go#L85)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> What's the deal with this? What time unit does `UnitProperties` return? Also you can extract the int64 casts into just casting the result of the div.
> </details>
> It's microseconds and I'm converting to seconds. I can't extract the `int64` cast because the division will then have a type mismatch `uint64` / `time.Duration`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/252)_

**Comment by mmlb** [comment]
Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/systemd/get.go, line 85 [r1]](https://reviewable.io:443/reviews/cerana/cerana/252#-KLwM_IxUQT0VNoEmj6o:-KLwwLgqKCJjvEtO9_nL:897087844) ([raw file](https://github.com/cerana/cerana/blob/2ad4e0fe817c8366f47aeb87834e6766e4759250/providers/systemd/get.go#L85)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> It's microseconds and I'm converting to seconds. I can't extract the `int64` cast because the division will then have a type mismatch `uint64` / `time.Duration`
> </details>
> see https://play.golang.org/p/2GxGITxzn0 for a cleaner/more-readable way

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/252)_

**Comment by bbickerton** [comment]
Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/systemd/get.go, line 85 [r1]](https://reviewable.io:443/reviews/cerana/cerana/252#-KLwM_IxUQT0VNoEmj6o:-KLx-APfakSSn2zftLwq:-499146009) ([raw file](https://github.com/cerana/cerana/blob/2ad4e0fe817c8366f47aeb87834e6766e4759250/providers/systemd/get.go#L85)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> see https://play.golang.org/p/2GxGITxzn0 for a cleaner/more-readable way
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/252)_

**Comment by mmlb** [comment]
Reviewed 21 of 21 files at r5, 7 of 7 files at r6, 15 of 15 files at r7, 6 of 6 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/252)_

**Pull request merged**
