### PR TITLE
providers/dhcp

### LINKED ISSUE #124: Layer 2 DHCP provider
## Issue Description

Implement Layer 2 DHCP provider
## Acceptance Criteria (How do we know when this is done?)

Based on 04/13/2016 architecture discussion, this card is complete when the following are implemented:
- [ ] GetLease
- [ ] MakeLease(update boot args)
- [ ] RemoveLease

### PR DESCRIPTION
**Pull request by mmlb**
#### Description:

Adds the dhcp provider.
#### Issues affected:

Resolves #124

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/233)

### CODE REVIEW

**Comment by bbickerton** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

_[cmd/dhcp-provider/main.go, line 16 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2WcQFbD0mHDYcliX_:-KL2WcQFbD0mHDYcliXa:1377403156) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/cmd/dhcp-provider/main.go#L16)):_

> ``` Go
> func dieOnError(err error) {
>   if err != nil {
>       log.Fatal("encountered an error during startup, error:", err)
> ```

This can be done as `log.WithField("error",err).Fatal("...")` so that the error is in a separate field. Easier to parse from the json if we ever try to do that kind of thing.

---

_[cmd/dhcp-provider/main.go, line 31 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2XI6zDhvw3XIP7d4c:-KL2XI6zDhvw3XIP7d4d:-1588237441) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/cmd/dhcp-provider/main.go#L31)):_

> ``` Go
>   config := dhcp.NewConfig(nil, nil)
>   pflag.IP("gateway", nil, "default gateway")
>   pflag.Duration("lease-duration", 24*time.Hour, "default lease duration")
> ```

The cli flag here is `lease-duration` but the lookup later is `leaseDuration`. They need to be the same, and the normalization task to extend (iirc) statspusher's flag/config hasn't been extended to the rest hasn't been completed. For now, pick one format here and in the lookup functions and then we'll clean it up with the other issue.

---

_[cmd/dhcp-provider/main.go, line 33 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2XeRFGO1ZVVVupina:-KL2XeRGqbSzQxZGumQb:-666945702) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/cmd/dhcp-provider/main.go#L33)):_

> ``` Go
>   pflag.Duration("lease-duration", 24*time.Hour, "default lease duration")
>   pflag.IPNet("network", defaultNetwork(), "network to manage dhcp addresses on")
>   pflag.StringSlice("dns-servers", nil, "dns servers")
> ```

Same as with `lease-duration`

---

_[providers/dhcp/config.go, line 60 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2YSJT6-Nv67lisMaO:-KL2YSJUzhuld0d9H6oP:-1586907312) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/config.go#L60)):_

> ``` Go
> 
> // LeaseDuration returns the client lease duration
> func (c *Config) LeaseDuration() (time.Duration, error) {
> ```

Here you can just use `return c.viper.GetDuration("leaseDuration")` and not worry about an error.

---

_[providers/dhcp/config.go, line 72 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2Z3hxwgo-eRnrnW6X:-KL2Z3hyO3gQIFruwcPk:227246678) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/config.go#L72)):_

> ``` Go
> func (c *Config) Gateway() (net.IP, error) {
>   var address string
>   if err := c.UnmarshalKey("gateway", &address); err != nil {
> ```

You can use `c.viper.GetString("gateway")`

---

_[providers/dhcp/config.go, line 87 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2ZBaa-Ba8bfiQmmz0:-KL2ZBaa-Ba8bfiQmmz1:-1405774931) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/config.go#L87)):_

> ``` Go
> func (c *Config) DNSServers() ([]net.IP, error) {
>   var addresses []string
>   if err := c.UnmarshalKey("dnsServers", &addresses); err != nil {
> ```

You can use `c.viper.GetStringSlice("dnsServers")`

---

_[providers/dhcp/config.go, line 106 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2ZLNTGV1vuTJDKLkZ:-KL2ZLNTGV1vuTJDKLk_:-1206784468) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/config.go#L106)):_

> ``` Go
> func (c *Config) Network() (*net.IPNet, error) {
>   var address string
>   if err := c.UnmarshalKey("network", &address); err != nil {
> ```

You can use `c.viper.GetString("network")`

---

_[providers/dhcp/config.go, line 111 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2ZaFCQl0KPIDTMrZl:-KL2ZaFCQl0KPIDTMrZm:1520248423) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/config.go#L111)):_

> ``` Go
> 
>   _, net, err := net.ParseCIDR(address)
>   if err != nil {
> ```

I think this can be `return net, err`

---

_[providers/dhcp/main.go, line 48 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2_vd1co_bDz0Bzmsa:-KL2_vd1co_bDz0Bzmsb:-208522552) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/main.go#L48)):_

> ``` Go
> 
> // New creates a new instance of DHCP.
> func New(config *Config, tracker *acomm.Tracker) (*DHCP, error) {
> ```

You're not storing the config and you're storing values from it to access directly. One of the things we wanted to do was to always have config access through Config so we can do things like config watching.

---

_[providers/dhcp/main.go, line 93 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2acsTXxpYCAhyHL-M:-KL2acsUNta4UxFDmf4y:232603320) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/main.go#L93)):_

> ``` Go
> }
> 
> func lookupMAC(tracker *acomm.Tracker, coord *url.URL, ip string) (string, error) {
> ```

Why not have this as a private method of `DHCP` which has references to the tracker and coordinator url already? Same goes for most of the private functions in here.

---

_[providers/dhcp/main.go, line 305 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2cPEjNdecT0vcqK2m:-KL2cPEjNdecT0vcqK2n:325040412) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/main.go#L305)):_

> ``` Go
>           if ok {
>               lease.Net.IP = net.ParseIP(addrs.IP)
>               fmt.Println("renewed lease:", lease)
> ```

Is this a debug that slipped in? If not, run it through logrus instead.

---

_[providers/dhcp/main.go, line 411 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2d0ZIGcxQ-OIdSAM3:-KL2d0ZIGcxQ-OIdSAM4:-2034343175) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/main.go#L411)):_

> ``` Go
>   mac, err := lookupMAC(d.tracker, d.coordinator, addrs.IP)
>   if err != nil {
>       fmt.Println("hi manny")
> ```

Debug statement slipped in

---

_[providers/dhcp/main_test.go, line 46 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2dSAXQlzjMpufEFQk:-KL2dSAXQlzjMpufEFQl:-1747996145) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/main_test.go#L46)):_

> ``` Go
> 
> func (s *DHCPS) SetupSuite() {
>   coordinator, err := test.NewCoordinator("")
> ```

This isn't being saved and stopped during suite cleanup.

---

_[providers/dhcp/main_test.go, line 82 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2dg6KDyPtzbguBWlB:-KL2dg6KDyPtzbguBWlC:-2122190413) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/main_test.go#L82)):_

> ``` Go
> 
> func (s *DHCPS) TearDownSuite() {
>   s.kv.Stop()
> ```

With kv.Mock registered to coordinator, you should just need to stop the coordinator.

---

_[providers/kv/kv.go, line 18 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2_JkK1g8zKRtGqPU5:-KL2_JkL2Nmicfkrt4mf:457837648) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/kv/kv.go#L18)):_

> ``` Go
> 
> // Value represents the value stored in a key, including the last modification index of the key
> type Value kv.Value
> ```

Can you explain why this alias is needed instead of just using `kv.Value` directly?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/233)_

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

_[cmd/dhcp-provider/main.go, line 16 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2WcQFbD0mHDYcliX_:-KL2vedFV8Kgd0V3HNLs:-733621218) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/cmd/dhcp-provider/main.go#L16)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> This can be done as `log.WithField("error",err).Fatal("...")` so that the error is in a separate field. Easier to parse from the json if we ever try to do that kind of thing.
> </details>
> I'm just going from prior art here. I'll do so here and add a card to update all other uses.

---

_[cmd/dhcp-provider/main.go, line 31 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2XI6zDhvw3XIP7d4c:-KL2vwOV3rAOsvf4LILF:867017618) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/cmd/dhcp-provider/main.go#L31)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> The cli flag here is `lease-duration` but the lookup later is `leaseDuration`. They need to be the same, and the normalization task to extend (iirc) statspusher's flag/config hasn't been extended to the rest hasn't been completed. For now, pick one format here and in the lookup functions and then we'll clean it up with the other issue.
> </details>
> good catch. hmm I believe this may be a similar situation in `kv-provider`

---

_[providers/dhcp/config.go, line 60 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2YSJT6-Nv67lisMaO:-KL33nsQ7On8CsUn2DFN:-499146009) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/config.go#L60)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Here you can just use `return c.viper.GetDuration("leaseDuration")` and not worry about an error.
> </details>
> Done.

---

_[providers/dhcp/config.go, line 111 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2ZaFCQl0KPIDTMrZl:-KL39ituexgXAUwZhfzH:782375925) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/config.go#L111)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> I think this can be `return net, err`
> </details>
> not necessarily, `net.ParseCIDR` could populate `net` (just noticed the bad name) and caller could ignore `err` and try to use `net`. Its a little paranoid, but meh I'd rather keep it.

---

_[providers/dhcp/main.go, line 48 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2_vd1co_bDz0Bzmsa:-KL3A5lP5ogMOMIgMwTV:-777813509) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/main.go#L48)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> You're not storing the config and you're storing values from it to access directly. One of the things we wanted to do was to always have config access through Config so we can do things like config watching.
> </details>
> ahh, yeah I got rid of storing the config because I'd rather not parse unchanging values multiple times. Actually I'm not sure the watching config values is a valid use case for the following reasons:
1. we should also be 12-factor(ish) and should be getting conf from env, so config file watching is not useful for prod
2. even if we were watching config file, I'd always just rather restart the whole app. Things are easier this way.
3. If we hold 1&2 to be true, then config watching is only useful for dev which can be hacked around using doing `inotify watch dev-env-file; source dev-env-file; exec'ing the binary; loop`

I'll drop the 1-time parsing, but opened up an issue to discuss this #246 .

---

_[providers/dhcp/main.go, line 93 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2acsTXxpYCAhyHL-M:-KL3BX41uMXLRNr7f9LS:-290416728) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/main.go#L93)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Why not have this as a private method of `DHCP` which has references to the tracker and coordinator url already? Same goes for most of the private functions in here.
> </details>
> meh I like pure functions, less load on the brain. I _really_ like only having methods when state is going to be mutated.

---

_[providers/dhcp/main.go, line 305 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2cPEjNdecT0vcqK2m:-KL3BgR_Ct9De3YsSJtf:-1530565430) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/main.go#L305)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Is this a debug that slipped in? If not, run it through logrus instead.
> </details>
> indeed

---

_[providers/dhcp/main.go, line 411 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2d0ZIGcxQ-OIdSAM3:-KL3BtAGhTyhN0tJ46Ct:-1444146900) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/main.go#L411)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Debug statement slipped in
> </details>
> no this I'd like to keep in ;)

---

_[providers/dhcp/main_test.go, line 82 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2dg6KDyPtzbguBWlB:-KL3C1xKtpqt6v1Xn0XC:-194899943) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/main_test.go#L82)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> With kv.Mock registered to coordinator, you should just need to stop the coordinator.
> </details>
> `kv.Mock` starts up a consul server, coordinator is not going to stop it.

---

_[providers/kv/kv.go, line 18 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2_JkK1g8zKRtGqPU5:-KL3F75cx3zlVUfAnuac:400087557) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/kv/kv.go#L18)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Can you explain why this alias is needed instead of just using `kv.Value` directly?
> </details>
> There was I think 1 minor reason and a mediumish... being that it won't show up in documentation.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/233)_

**Comment by mmlb** [comment]
Review status: 11 of 15 files reviewed at latest revision, 15 unresolved discussions.

---

_[cmd/dhcp-provider/main.go, line 16 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2WcQFbD0mHDYcliX_:-KL4HfVw78O7wIARVvMd:-499146009) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/cmd/dhcp-provider/main.go#L16)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> I'm just going from prior art here. I'll do so here and add a card to update all other uses.
> </details>
> Done.

---

_[cmd/dhcp-provider/main.go, line 31 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2XI6zDhvw3XIP7d4c:-KL4HhoK8Mgs1WkI-ulh:-499146009) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/cmd/dhcp-provider/main.go#L31)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> good catch. hmm I believe this may be a similar situation in `kv-provider`
> </details>
> Done.

---

_[cmd/dhcp-provider/main.go, line 33 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2XeRFGO1ZVVVupina:-KL4HjXqB3R_OFAqsIAF:-499146009) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/cmd/dhcp-provider/main.go#L33)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Same as with `lease-duration`
> </details>
> Done.

---

_[providers/dhcp/config.go, line 87 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2ZBaa-Ba8bfiQmmz0:-KL4HsmSSNYQ2swBkQUh:-499146009) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/config.go#L87)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> You can use `c.viper.GetStringSlice("dnsServers")`
> </details>
> Done.

---

_[providers/dhcp/config.go, line 106 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2ZLNTGV1vuTJDKLkZ:-KL4HupnZS2TDx_dRVfp:-499146009) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/config.go#L106)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> You can use `c.viper.GetString("network")`
> </details>
> Done.

---

_[providers/dhcp/main.go, line 305 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2cPEjNdecT0vcqK2m:-KL4I0HW4QGDlUpz_qZ0:-499146009) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/main.go#L305)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> indeed
> </details>
> Done.

---

_[providers/dhcp/main.go, line 411 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2d0ZIGcxQ-OIdSAM3:-KL4I3tx1dY2Cibz077V:-499146009) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/main.go#L411)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> no this I'd like to keep in ;)
> </details>
> Done.

---

_[providers/dhcp/main_test.go, line 46 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2dSAXQlzjMpufEFQk:-KL4I63ya6AwhJfK6xku:-499146009) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/main_test.go#L46)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> This isn't being saved and stopped during suite cleanup.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/233)_

**Comment by bbickerton** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

_[providers/dhcp/config.go, line 67 [r2]](https://reviewable.io:443/reviews/cerana/cerana/233#-KLHGJGAyF6Y7BbK5VmO:-KLHGJGAyF6Y7BbK5VmP:-1121182034) ([raw file](https://github.com/cerana/cerana/blob/de839d9e4b88d6ee920f19db3d22e86de4c428af/providers/dhcp/config.go#L67)):_

> ``` Go
> func (c *Config) Gateway() net.IP {
>   ip := net.ParseIP(c.viper.GetString("gateway"))
>   if ip == nil {
> ```

could just `return net.ParseIP(c.viper.GetString("gateway"))` ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/233)_

**Comment by mmlb** [comment]
Review status: 14 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

_[providers/dhcp/config.go, line 72 [r1]](https://reviewable.io:443/reviews/cerana/cerana/233#-KL2Z3hxwgo-eRnrnW6X:-KLHMeQAktkh6R_ENM_1:-499146009) ([raw file](https://github.com/cerana/cerana/blob/128e057e13802bb45a5856f1031db151c26a0fca/providers/dhcp/config.go#L72)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> You can use `c.viper.GetString("gateway")`
> </details>
> Done.

---

_[providers/dhcp/config.go, line 67 [r2]](https://reviewable.io:443/reviews/cerana/cerana/233#-KLHGJGAyF6Y7BbK5VmO:-KLHNU2kicaOxuBUmr87:-499146009) ([raw file](https://github.com/cerana/cerana/blob/de839d9e4b88d6ee920f19db3d22e86de4c428af/providers/dhcp/config.go#L67)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> could just `return net.ParseIP(c.viper.GetString("gateway"))` ?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/233)_

**Comment by bbickerton** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/233)_

**Comment by bbickerton** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/233)_

**Comment by bbickerton** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/dhcp/main_test.go, line 62 [r5]](https://reviewable.io:443/reviews/cerana/cerana/233#-KLIWDfU3NJ_LtblBx6G:-KLIWDfVjOToiV1_AdC0:-1594955021) ([raw file](https://github.com/cerana/cerana/blob/625525ae1058f194f55bccfd4c5e0d1d88c32219/providers/dhcp/main_test.go#L62)):_

> ``` Go
>   s.Require().NoError(s.config.LoadConfig())
>   s.Require().NoError(s.config.SetupLogging())
>   s.Require().NoError(flagset.Parse([]string{}))
> ```

flagset parsing should come before LoadConfig.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/233)_

**Comment by mmlb** [comment]
Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/dhcp/main_test.go, line 62 [r5]](https://reviewable.io:443/reviews/cerana/cerana/233#-KLIWDfU3NJ_LtblBx6G:-KLIWV9FbMlvRc0O-zv2:-499146009) ([raw file](https://github.com/cerana/cerana/blob/625525ae1058f194f55bccfd4c5e0d1d88c32219/providers/dhcp/main_test.go#L62)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> flagset parsing should come before LoadConfig.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/233)_

**Comment by bbickerton** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/233)_

**Pull request merged**
