### PR TITLE
Add shellcheck and shfmt targets to main Makefile

### PR DESCRIPTION
**Pull request by nshalman**
#### Description:
- Make it easier to enforce shellcheck and shfmt across the whole repo.
- Update the Travis environment to be able to run shellcheck and shfmt so that we can enable these for CI testing.

Future work:
- Make everying under `build/` report clean with these targets

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/353)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[.travis/deps.sh, line 40 [r1]](https://reviewable.io:443/reviews/cerana/cerana/353#-KQ2X9Cb4Mp3BokGbP9A:-KQ2X9Cb4Mp3BokGbP9B:b-f89phb) ([raw file](https://github.com/cerana/cerana/blob/e344570cb9fc40d08d2aeeba01bfa1a944b4f128/.travis/deps.sh#L40)):_

> ``` Shell
>     gometalinter --install --update
>     go get github.com/mvdan/sh/cmd/shfmt
>     curl -LO https://us-east.manta.joyent.com/nahamu/public/cerana/shellcheck_0.4.4_amd64.deb \
> ```

Why don't we just fetch it from ubuntu repos?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/353)_

**Comment by nshalman** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[.travis/deps.sh, line 40 [r1]](https://reviewable.io:443/reviews/cerana/cerana/353#-KQ2X9Cb4Mp3BokGbP9A:-KQ2_2CkeAKhah0fQVwy:b4dj9n6) ([raw file](https://github.com/cerana/cerana/blob/e344570cb9fc40d08d2aeeba01bfa1a944b4f128/.travis/deps.sh#L40)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> Why don't we just fetch it from ubuntu repos?
> </details>
> Short answer is no. I did try mightily. Those will only give me an outdated version. I don't like this solution, but  unlike everything else I tried, this works.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/353)_

**Comment by nshalman** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[.travis/deps.sh, line 40 [r1]](https://reviewable.io:443/reviews/cerana/cerana/353#-KQ2X9Cb4Mp3BokGbP9A:-KQ2_HW__tnb_IA5_dwC:bqrc6gz) ([raw file](https://github.com/cerana/cerana/blob/e344570cb9fc40d08d2aeeba01bfa1a944b4f128/.travis/deps.sh#L40)):_
<details><summary>

<i>Previously, nshalman (Nahum Shalman) wrote…</i></summary>



> Short answer is no. I did try mightily. Those will only give me an outdated version. I don't like this solution, but  unlike everything else I tried, this works.
> </details>
> To clarify, that .deb I built myself on an ubuntu 14.04 system using fpm after manually getting Cabal to build the shellcheck binary that's inside.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/353)_

**Comment by nshalman** [comment]
This branch now includes code to compile and cache shellcheck within Travis.

**Comment by nshalman** [comment]
Review status: 6 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

_[.travis/deps.sh, line 40 [r1]](https://reviewable.io:443/reviews/cerana/cerana/353#-KQ2X9Cb4Mp3BokGbP9A:-KQWcY09BLmlLc7owQly:b-5fgu6z) ([raw file](https://github.com/cerana/cerana/blob/e344570cb9fc40d08d2aeeba01bfa1a944b4f128/.travis/deps.sh#L40)):_
<details><summary>

<i>Previously, nshalman (Nahum Shalman) wrote…</i></summary>



> To clarify, that .deb I built myself on an ubuntu 14.04 system using fpm after manually getting Cabal to build the shellcheck binary that's inside.
> </details>
> Replaced with a cleaner method that builds and caches within Travis. Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/353)_

**Comment by mmlb** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/353)_

**Pull request merged**
