### PR TITLE
cmd/bootserver - Wrap errors

### PR DESCRIPTION
**Pull request by bbickerton**
#### Issues affected:

Relates to #308

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/338)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[cmd/bootserver/main.go, line 130 [r1]](https://reviewable.io:443/reviews/cerana/cerana/338#-KPTFsO_rZ594isf09j0:-KPTFsO_rZ594isf09j1:b-915lwk) ([raw file](https://github.com/cerana/cerana/blob/4afeee7fec7db63c417fe8816a2fad19f8d4d228/cmd/bootserver/main.go#L130)):_

> ``` Go
> 
>   ip, _, err := net.ParseCIDR(ips[0].String())
>   logrusx.DieOnError(errors.Wrapv(err, map[string]interface{}{"ip": ips[0].String()}), "parse ip address")
> ```

`.String()` should be unnecessary I think

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/338)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[cmd/bootserver/main.go, line 130 [r1]](https://reviewable.io:443/reviews/cerana/cerana/338#-KPTFsO_rZ594isf09j0:-KPTeSPeRzMb09RJiyqg:b-p19761) ([raw file](https://github.com/cerana/cerana/blob/4afeee7fec7db63c417fe8816a2fad19f8d4d228/cmd/bootserver/main.go#L130)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> `.String()` should be unnecessary I think
> </details>
> I used `.String()` so that it would capture exactly what was passed to `net.ParseCIDR()`. Probably should have named the field "cidr" instead. Would you be ok with the string if i changed the name?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/338)_

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[cmd/bootserver/main.go, line 130 [r1]](https://reviewable.io:443/reviews/cerana/cerana/338#-KPTFsO_rZ594isf09j0:-KPTkQBWTD47JBEN874G:bshmgbi) ([raw file](https://github.com/cerana/cerana/blob/4afeee7fec7db63c417fe8816a2fad19f8d4d228/cmd/bootserver/main.go#L130)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> I used `.String()` so that it would capture exactly what was passed to `net.ParseCIDR()`. Probably should have named the field "cidr" instead. Would you be ok with the string if i changed the name?
> </details>
> net or subnet is probably better. (I was confused and thought that MarshalJSON without `String()` would be the same as calling `String()`, but now I remember that that is not the case)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/338)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[cmd/bootserver/main.go, line 130 [r1]](https://reviewable.io:443/reviews/cerana/cerana/338#-KPTFsO_rZ594isf09j0:-KPTlFGqd3fixN1FO2Zx:b-896fix) ([raw file](https://github.com/cerana/cerana/blob/4afeee7fec7db63c417fe8816a2fad19f8d4d228/cmd/bootserver/main.go#L130)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> net or subnet is probably better. (I was confused and thought that MarshalJSON without `String()` would be the same as calling `String()`, but now I remember that that is not the case)
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/338)_

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/338)_

**Pull request merged**
