### PR TITLE
clusterconf - Wrap errors

### PR DESCRIPTION
**Pull request by bbickerton**
#### Description:

Wrap clusterconf errors with errors package
#### Issues affected:

Related #308

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/331)

### CODE REVIEW

**Comment by mmlb** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/clusterconf/bundle.go, line 460 [r1]](https://reviewable.io:443/reviews/cerana/cerana/331#-KPSiLDPN3P5Ss-1D5hv:-KPSiLDPN3P5Ss-1D5hw:b55wx2r) ([raw file](https://github.com/cerana/cerana/blob/cfa991bb965dc9de13465ba186f4eff02bd2b328/providers/clusterconf/bundle.go#L460)):_

> ``` Go
>       }
>   }
>   return nil, fmt.Errorf("bundle overlay failed: %+v", errors)
> ```

Shouldn't errs be in the data?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/331)_

**Comment by mmlb** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/331)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/clusterconf/bundle.go, line 460 [r1]](https://reviewable.io:443/reviews/cerana/cerana/331#-KPSiLDPN3P5Ss-1D5hv:-KPT3a-J4buuIQ15lwSP:b-bcophg) ([raw file](https://github.com/cerana/cerana/blob/cfa991bb965dc9de13465ba186f4eff02bd2b328/providers/clusterconf/bundle.go#L460)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> Shouldn't errs be in the data?
> </details>
> Maybe both?. I wasn't sure how best to handle a situation with multiple errors, especially one where it will be crossing the acomm boundary. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/331)_

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/clusterconf/bundle.go, line 460 [r1]](https://reviewable.io:443/reviews/cerana/cerana/331#-KPSiLDPN3P5Ss-1D5hv:-KPTHO6BYbXVOqKOVWLT:b-1e7fh2) ([raw file](https://github.com/cerana/cerana/blob/cfa991bb965dc9de13465ba186f4eff02bd2b328/providers/clusterconf/bundle.go#L460)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Maybe both?. I wasn't sure how best to handle a situation with multiple errors, especially one where it will be crossing the acomm boundary. 
> </details>
> idk. If it's being logged fully before being sent out then it's logged. Callers shouldn't really care about the individual errors, they will just go into error'ed mode. The errors were probably just useful for logging, but we've already taken care of that.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/331)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/clusterconf/bundle.go, line 460 [r1]](https://reviewable.io:443/reviews/cerana/cerana/331#-KPSiLDPN3P5Ss-1D5hv:-KPTfEWh7fAqTsoxQ1VT:byksuul) ([raw file](https://github.com/cerana/cerana/blob/cfa991bb965dc9de13465ba186f4eff02bd2b328/providers/clusterconf/bundle.go#L460)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> idk. If it's being logged fully before being sent out then it's logged. Callers shouldn't really care about the individual errors, they will just go into error'ed mode. The errors were probably just useful for logging, but we've already taken care of that.
> </details>
> True. Removed specific errors from the error message because, as you said, caller will just go into error mode, and added them to the data for logging.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/331)_

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/331)_

**Comment by mmlb** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/331)_

**Pull request merged**
