### PR TITLE
Add CODE_OF_CONDUCT.md with abuse@cerana.org email address

### LINKED ISSUE #62: Cerana needs a Code of Conduct
<a href="https://github.com/nshalman"></img></a> **Issue by [nshalman](https://github.com/nshalman)**
_Tue Mar 22 20:18:13 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/62_

---
## Issue Description

We need a Code of Conduct in place before the hordes of community contributors show up.
I'll be investigating a few options with notes in this issue and will follow up with a pull request of my recommendation.
## Related Issues
#138 - Cerana Mailing List (Dependency)

### PR DESCRIPTION
**Pull request by nshalman**
## Issues affected/resolved

Resolves #62

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/146)

### CODE REVIEW

**Comment by joshie** [comment]
LGTM

**Comment by bbickerton** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

_[CODE_OF_CONDUCT.md, line 7 [r1]](https://reviewable.io:443/reviews/cerana/cerana/146#-KFK5npEHeeagksieuU3:-KFK5npEHeeagksieuU4:2121067588) ([raw file](https://github.com/cerana/cerana/blob/9c8d15265eaeb660d520f442c9c95c6b8a8b2416/CODE_OF_CONDUCT.md#L7)):_
Does explicitly specifying special protected aspects here leave us open to things that aren't explicitly covered? Would it be better to use some more general phrasing, or even just end it after "everyone"?

---

_[CODE_OF_CONDUCT.md, line 53 [r1]](https://reviewable.io:443/reviews/cerana/cerana/146#-KFK6LadyHNgHlv8cSnb:-KFK6LaeEq9YKmi0033K:1871623433) ([raw file](https://github.com/cerana/cerana/blob/9c8d15265eaeb660d520f442c9c95c6b8a8b2416/CODE_OF_CONDUCT.md#L53)):_
Do we want to add language explicitly saying that this does not cover personal accounts, or is the implicit enough? This was a big hoopla recently with some project, I forget which one, where there were calls to remove a contributor based on his personal tweets.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/146)_

**Comment by joshie** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

_[CODE_OF_CONDUCT.md, line 7 [r1]](https://reviewable.io:443/reviews/cerana/cerana/146#-KFK5npEHeeagksieuU3:-KFK90B5op2ouMIPCdfd:1608298890) ([raw file](https://github.com/cerana/cerana/blob/9c8d15265eaeb660d520f442c9c95c6b8a8b2416/CODE_OF_CONDUCT.md#L7)):_
For the record, this is word for word contributor-covenant.org and can probably be taken up in discussions about the wording there.

As for if we are okay with the wording, I think so. Everyone is all encompassing, and everything listed after reminds people that such things are a subset of everyone. "Needs to be said" and "doesn't hurt to say it" aren't mutually exclusive, and while I personally think it doesn't "need to be said", I do think it doesn't hurt.

---

_[CODE_OF_CONDUCT.md, line 53 [r1]](https://reviewable.io:443/reviews/cerana/cerana/146#-KFK6LadyHNgHlv8cSnb:-KFK7ySuaI9od5uC80qa:-448488403) ([raw file](https://github.com/cerana/cerana/blob/9c8d15265eaeb660d520f442c9c95c6b8a8b2416/CODE_OF_CONDUCT.md#L53)):_
I personally believe the implicit language is enough. If it arises, we can clarify then that such things are out of scope and we won't be removing the contributor.  Both situations would probably have the same upsetting end result to people who want to police unrelated behavior, but putting a specific clause in there might generate outrage ahead of time regardless of if it ever applied.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/146)_

**Comment by mmlb** [comment]
LGTM

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/146#-:-KFKB577WUa8dOQx6SWg:676834233)_

**Pull request merged**
