### PR TITLE
Tool to roll a ZFS dataset back to a pristine clone of an origin dataset/snapshot

### LINKED ISSUE #283: Script to handle ZFS clone and rollback for systemd units
#### Issue Description

Get source and destination from environment variables.
Create clone if it doesn't exist
Create pristine snapshot if it doesn't exist
Rollback to pristine snapshot
#### Related Tickets

Related to #284

### PR DESCRIPTION
**Pull request by nshalman**
#### Description:

Does what it says in the PR title.
#### Issues affected:

Resolves #283

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/301)

### CODE REVIEW

**Comment by bbickerton** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[boot/bin/rollback_clone, line 13 [r1]](https://reviewable.io:443/reviews/cerana/cerana/301#-KNYHwiEFMqvWoS-aRgn:-KNYHwiEFMqvWoS-aRgo:1807559356) ([raw file](https://github.com/cerana/cerana/blob/e08253008b0ffbcd1d0b69aa6f495e6b2a433535/boot/bin/rollback_clone#L13)):_

> ```
> # If SOURCE is a snapshot, this is relatively simple
> # If SOURCE is just a dataset, use the newest snapshot of it.
> # I no snapshot exists of the SOURCE dataset, create one to use.
> ```

"If" typo

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/301)_

**Comment by nshalman** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[boot/bin/rollback_clone, line 13 [r1]](https://reviewable.io:443/reviews/cerana/cerana/301#-KNYHwiEFMqvWoS-aRgn:-KNYLqT30_PNPZgh2udO:1758359711) ([raw file](https://github.com/cerana/cerana/blob/e08253008b0ffbcd1d0b69aa6f495e6b2a433535/boot/bin/rollback_clone#L13)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> "If" typo
> </details>
> Fixed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/301)_

**Comment by bbickerton** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/301)_

**Comment by mmlb** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/301)_

**Pull request merged**
