### PR TITLE
Bootserver

### LINKED ISSUE #125: Layer 2 boot service
## Issue Description

Implement Layer DHCP service
## Acceptance Criteria (How do we know when this is done?)

TBD

### PR DESCRIPTION
**Pull request by mmlb**
#### Issues affected:

Resolves #125

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/296)

### CODE REVIEW

**Comment by mmlb** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

_[cmd/bootserver/main_test.go, line 194 [r1]](https://reviewable.io:443/reviews/cerana/cerana/296#-KNDBLatkKHPAgIUmYfg:-KNDBLatkKHPAgIUmYfh:778611281) ([raw file](https://github.com/cerana/cerana/blob/bad75fbb067eecd02bf22f33118af908bad90be6/cmd/bootserver/main_test.go#L194)):_

> ``` Go
>           ip = net.ParseIP(ips[t.mac])
>       case t.dupe:
>           // using dupe to any other mac's ip
> ```

this comment doesn't make any sense, and the loop doesn't break out early, will fix and update

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/296)_

**Comment by mmlb** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

_[cmd/bootserver/main_test.go, line 194 [r1]](https://reviewable.io:443/reviews/cerana/cerana/296#-KNDBLatkKHPAgIUmYfg:-KNDBpUyoYzAMV-B-o71:-499146009) ([raw file](https://github.com/cerana/cerana/blob/bad75fbb067eecd02bf22f33118af908bad90be6/cmd/bootserver/main_test.go#L194)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> this comment doesn't make any sense, and the loop doesn't break out early, will fix and update
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/296)_

**Comment by bbickerton** [comment]
Reviewed 18 of 19 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[providers/clusterconf/dhcp.go, line 36 [r2]](https://reviewable.io:443/reviews/cerana/cerana/296#-KNDEuJ86UMIBEGeWk20:-KNDEuJ9CulYa5LG3Luo:-1349895105) ([raw file](https://github.com/cerana/cerana/blob/8dbc78cc9ed15c833c5e6339719bb1ef32da45ae/providers/clusterconf/dhcp.go#L36)):_

> ``` Go
> }
> 
> func validateDHCPConf(conf *DHCPConfig) error {
> ```

Why not a method of `DHCPConfig`?

---

_[providers/clusterconf/dhcp.go, line 67 [r2]](https://reviewable.io:443/reviews/cerana/cerana/296#-KNDFJt2kDMrAyLwMYop:-KNDFJt2kDMrAyLwMYoq:1065545811) ([raw file](https://github.com/cerana/cerana/blob/8dbc78cc9ed15c833c5e6339719bb1ef32da45ae/providers/clusterconf/dhcp.go#L67)):_

> ``` Go
>   }
> 
>   index := uint64(0)
> ```

Why isn't the index being tracked in DHCPConfig so that after someone does a Get and updates some values, it can try to set without blowing any changes away? This doesn't really protect against much doing it here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/296)_

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[providers/clusterconf/dhcp.go, line 36 [r2]](https://reviewable.io:443/reviews/cerana/cerana/296#-KNDEuJ86UMIBEGeWk20:-KNDVRjPoMChdutuP0SZ:-2128432884) ([raw file](https://github.com/cerana/cerana/blob/8dbc78cc9ed15c833c5e6339719bb1ef32da45ae/providers/clusterconf/dhcp.go#L36)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Why not a method of `DHCPConfig`?
> </details>
> hmmm no reason, will respin.

---

_[providers/clusterconf/dhcp.go, line 67 [r2]](https://reviewable.io:443/reviews/cerana/cerana/296#-KNDFJt2kDMrAyLwMYop:-KNDWImdu83oCkNDs4dH:-1384777525) ([raw file](https://github.com/cerana/cerana/blob/8dbc78cc9ed15c833c5e6339719bb1ef32da45ae/providers/clusterconf/dhcp.go#L67)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Why isn't the index being tracked in DHCPConfig so that after someone does a Get and updates some values, it can try to set without blowing any changes away? This doesn't really protect against much doing it here.
> </details>
> Well as things stand right now that situation is impossible. No one should be updating dhcp after its been set. We do plan on allowing that situation, but it needs a lot of thought first. I imagine it will be stored then.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/296)_

**Comment by mmlb** [comment]
Review status: 16 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

_[providers/clusterconf/dhcp.go, line 36 [r2]](https://reviewable.io:443/reviews/cerana/cerana/296#-KNDEuJ86UMIBEGeWk20:-KND_KmjcMy1ThU8WZya:-499146009) ([raw file](https://github.com/cerana/cerana/blob/8dbc78cc9ed15c833c5e6339719bb1ef32da45ae/providers/clusterconf/dhcp.go#L36)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> hmmm no reason, will respin.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/296)_

**Comment by bbickerton** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[providers/clusterconf/dhcp.go, line 67 [r2]](https://reviewable.io:443/reviews/cerana/cerana/296#-KNDFJt2kDMrAyLwMYop:-KNDgOnakKS_Xv4z5o6i:-1024557721) ([raw file](https://github.com/cerana/cerana/blob/8dbc78cc9ed15c833c5e6339719bb1ef32da45ae/providers/clusterconf/dhcp.go#L67)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> Well as things stand right now that situation is impossible. No one should be updating dhcp after its been set. We do plan on allowing that situation, but it needs a lot of thought first. I imagine it will be stored then.
> </details>
> Fair enough.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/296)_

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[providers/clusterconf/dhcp.go, line 67 [r2]](https://reviewable.io:443/reviews/cerana/cerana/296#-KNDFJt2kDMrAyLwMYop:-KNE8oCysgk52RyThCA2:-499146009) ([raw file](https://github.com/cerana/cerana/blob/8dbc78cc9ed15c833c5e6339719bb1ef32da45ae/providers/clusterconf/dhcp.go#L67)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Fair enough.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/296)_

**Pull request merged**
