### PR TITLE
Clusterconfig Provider

### LINKED ISSUE #145: Layer 2 - Cluster Config Provider
## Issue Description

This provider will handle various configurations, backed by the Layer 2 KV Provider
## Acceptance Criteria (How do we know when this is done?)

The following tasks are functional:
- [ ] Update-dataset
- [ ] Register-dataset-heartbeat
- [ ] Delete-dataset
- [ ] Get-dataset
- [ ] Update-service
- [ ] Get-service
- [ ] Delete-service
- [ ] Create-bundle
- [ ] Register-bundle-heartbeat
- [ ] Get-bundle
- [ ] Delete-bundle
- [ ] Register-node(-heartbeat)?
- [ ] Set-default-options
- [ ] Get-default-options
## Related Tickets

Completion is blocked by #123 Layer 2 KV provider
## Additional Info

```
Data Architecture Tree
    dataset
        id: uuid
        parent: uuid to be replicated from
        parent_same_machine: boolean
        read-only: boolean
        nfs: boolean
        redundancy: integer
        quota: integer
        /nodes (TTL records)
            “ip”: boolean indicating if in use
    service
        id: uuid
        dataset: uuid
        cmd: array of strings
        /healthcheck
            /{id}
                {protocol_provider}: parameters
        /limits
            Cpu:
            Memory:
            Processes:
            ...
        /env
            ENVVAR_NAME: value
    bundle
        id: integer
        /datasets
            /{your-name}
                uuid: Optional dataset-uuid
                type: zfs or ramdisk
                quota: optional quota
        /services
            /{service-uuid}
                (override anything but id and dataset)
                /limits
                    [optional overrides]
                /env
                    ENVVAR_NAME: value
                /datasets
                    {your-name}: mount_point,rw
        redundancy: integer
        /nodes (TTL records)
            “serial”: “ip”
        Ports
            /{port-number}
                Public: boolean
                Connected_bundles: array of ids
                External_port: integer
    /nodes
        /{machine-serial} TTL’d (ip address for this, or maybe mac) (self assigned ip config)
            Heartbeat: last write
            Memory_free
            Cpu_free
            Disk_free
            Memory_total
            Cpu_total
            Disk_total
    /historical_entries
        /{machine-serial}
            /{heartbeat}
                The shit under nodes
    /cluster_config
        zfs: auto/manual
```

### PR DESCRIPTION
**Pull request by bbickerton**
## Issues affected/resolved

(See https://github.com/blog/1506-closing-issues-via-pull-requests)
Resolves #145
## Description:

Cluster configuration provider. Declare Datasets, Services, Bundles, Default Configs. Registers latest heartbeats for each plus Nodes and their history. Reads and writes via the KV provider.

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/178)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[cmd/clusterconfig-provider/clusterconfig-provider, line 0 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo5tzOemN43D9iMif_:-KIo5tzOemN43D9iMifa:-401070156) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/cmd/clusterconfig-provider/clusterconfig-provider#L0)):_
Need to get rid of this from history

---

_[cmd/clusterconfig-provider/config.json, line 4 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo69Y4Waeh62DhokBB:-KIo69Y4Waeh62DhokBC:-2049708932) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/cmd/clusterconfig-provider/config.json#L4)):_

> ``` JSON
>     "service_name": "systemd-provider",
>     "coordinator_url": "unix:///tmp/mistify/coordinator/coordinator.sock",
>     "dataset-ttl": 60000000000,
> ```

If you use `time.ParseDuration()` you can use nicer looking values like `1s` or `1m` or `1m15s` which avoids counting long # of 0s here and in cli.

---

_[providers/clusterconf/bundle.go, line 24 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo8EUaVPEz1JR3Tsyc:-KIo8EUaVPEz1JR3Tsyd:-1826409416) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/providers/clusterconf/bundle.go#L24)):_

> ``` Go
>   c *ClusterConf
>   // Nodes contains the set of nodes on which the dataset is currently in use.
>   // THe map keys are serials.
> ```

s/TH/th/
serial what?

---

_[providers/clusterconf/bundle.go, line 32 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo8LT6t7SNAtrNHy3g:-KIo8LT6t7SNAtrNHy3h:1425481744) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/providers/clusterconf/bundle.go#L32)):_

> ``` Go
> // BundleConf is the configuration of a bundle.
> type BundleConf struct {
>   ID         int                       `json:"id"`
> ```

uint or maybe uint64, I don't expected to see negative ids.

---

_[providers/clusterconf/bundle.go, line 136 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo9-2R46y9SKtSvXOi:-KIo9-2R46y9SKtSvXOj:-806887948) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/providers/clusterconf/bundle.go#L136)):_

> ``` Go
> }
> 
> // UpdateBundle creates or updates a bundle config. When updating, a Get should first be performed and the modified Bundle passed back.
> ```

New line after the .

---

_[providers/clusterconf/bundle.go, line 255 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo9MFlCQ-ejdeDiSxC:-KIo9MFlCQ-ejdeDiSxD:-924433169) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/providers/clusterconf/bundle.go#L255)):_

> ``` Go
> }
> 
> // update saves the core bundle config. It will not modify nodes.
> ```

new line before `It`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/178)_

**Comment by bbickerton** [comment]
Review status: 20 of 21 files reviewed at latest revision, 6 unresolved discussions.

---

_[cmd/clusterconfig-provider/config.json, line 4 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo69Y4Waeh62DhokBB:-KJ7k8cUXeabnnaDjFQN:-499146009) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/cmd/clusterconfig-provider/config.json#L4)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> If you use `time.ParseDuration()` you can use nicer looking values like `1s` or `1m` or `1m15s` which avoids counting long # of 0s here and in cli.
> </details>
> Done.

---

_[providers/clusterconf/bundle.go, line 24 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo8EUaVPEz1JR3Tsyc:-KJ7ki67SD3yOC_tzG5H:-499146009) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/providers/clusterconf/bundle.go#L24)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> s/TH/th/
> serial what?
> </details>
> Done.

---

_[providers/clusterconf/bundle.go, line 32 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo8LT6t7SNAtrNHy3g:-KJ7kFY1JJUfUC76jhQZ:676891207) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/providers/clusterconf/bundle.go#L32)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> uint or maybe uint64, I don't expected to see negative ids.
> </details>
> I went with `int` for ease of use compared to `uint64`. Thoughts?

---

_[providers/clusterconf/bundle.go, line 136 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo9-2R46y9SKtSvXOi:-KJ7kSTijMD7jCk26ybE:-499146009) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/providers/clusterconf/bundle.go#L136)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> New line after the .
> </details>
> Done.

---

_[providers/clusterconf/bundle.go, line 255 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo9MFlCQ-ejdeDiSxC:-KJ7kXe9e9DBd9uzhLOM:-499146009) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/providers/clusterconf/bundle.go#L255)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> new line before `It`
> </details>
> Done.

---

_[cmd/clusterconfig-provider/clusterconfig-provider, line  [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo5tzOemN43D9iMif_:-KJ7kZJ5ICO8WlmYUF2l:-499146009) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/cmd/clusterconfig-provider/clusterconfig-provider#L)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> Need to get rid of this from history
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/178)_

**Comment by mmlb** [comment]
Reviewed 1 of 2 files at r2, 13 of 14 files at r3, 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[cmd/clusterconfig-provider/config.json, line 4 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo69Y4Waeh62DhokBB:-KJM9o-jAqH1Bnj8TDpo:873234283) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/cmd/clusterconfig-provider/config.json#L4)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Done.
> </details>
> doesn't seem like it. This should be a string like "6min" or w/e it is.

---

_[providers/clusterconf/bundle.go, line 24 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo8EUaVPEz1JR3Tsyc:-KJMABiqVrDtBLhzpPMP:-1747053362) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/providers/clusterconf/bundle.go#L24)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Done.
> </details>
> Serials still isn't really explained

---

_[providers/clusterconf/bundle.go, line 32 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo8LT6t7SNAtrNHy3g:-KJMAHETKFqveHEQqwTC:1190115910) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/providers/clusterconf/bundle.go#L32)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> I went with `int` for ease of use compared to `uint64`. Thoughts?
> </details>
> hmmm should definitely not be bare `int` since thats not guaranteed to be of a specific size. So might as well go with `uint64`

---

_[providers/clusterconf/clusterconf_test.go, line 15 [r5]](https://reviewable.io:443/reviews/cerana/cerana/178#-KJME9SLfl0tmtu63d4q:-KJME9SMginUZMK_MCFI:167753749) ([raw file](https://github.com/cerana/cerana/blob/29d86a1f867df59ede6df04c14738a15fda4f0f7/providers/clusterconf/clusterconf_test.go#L15)):_

> ``` Go
>   "github.com/cerana/cerana/provider"
>   "github.com/cerana/cerana/providers/clusterconf"
>   kvp "github.com/cerana/cerana/providers/kv"
> ```

why the rename?

---

_[providers/kv/basic.go, line 34 [r5]](https://reviewable.io:443/reviews/cerana/cerana/178#-KJMUUbI1a0rT8KAdiT4:-KJMUUbI1a0rT8KAdiT5:1625478395) ([raw file](https://github.com/cerana/cerana/blob/29d86a1f867df59ede6df04c14738a15fda4f0f7/providers/kv/basic.go#L34)):_

> ``` Go
>   }
> 
>   if !args.Recursive && args.Key == "" {
> ```

curious if there was a reason why you put `!args.Recursive` first? I prefer the alternate (for some reason) but it doesn't make a difference.

---

_[providers/kv/mock.go, line 16 [r5]](https://reviewable.io:443/reviews/cerana/cerana/178#-KJMV7PvTcKSZzSreuBy:-KJMV7PvTcKSZzSreuBz:350338361) ([raw file](https://github.com/cerana/cerana/blob/29d86a1f867df59ede6df04c14738a15fda4f0f7/providers/kv/mock.go#L16)):_

> ``` Go
> // Mock is a mock KV provider
> type Mock struct {
>   *KV
> ```

why is this necessary?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/178)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[providers/kv/basic.go, line 34 [r5]](https://reviewable.io:443/reviews/cerana/cerana/178#-KJMUUbI1a0rT8KAdiT4:-KJMXOIA8CX5fuCRuiO9:-722554470) ([raw file](https://github.com/cerana/cerana/blob/29d86a1f867df59ede6df04c14738a15fda4f0f7/providers/kv/basic.go#L34)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> curious if there was a reason why you put `!args.Recursive` first? I prefer the alternate (for some reason) but it doesn't make a difference.
> </details>
> I put `!args.Recursive` first because that's the context in which the check on `args.Key` matters.

---

_[providers/kv/mock.go, line 16 [r5]](https://reviewable.io:443/reviews/cerana/cerana/178#-KJMV7PvTcKSZzSreuBy:-KJMXdlH3BIhF35w3Pkg:-57463036) ([raw file](https://github.com/cerana/cerana/blob/29d86a1f867df59ede6df04c14738a15fda4f0f7/providers/kv/mock.go#L16)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> why is this necessary?
> </details>
> When it was just a property, `Mock` did not satisfy the `provider.Provider` interface, as the methods didn't bubble up.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/178)_

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[providers/kv/mock.go, line 16 [r5]](https://reviewable.io:443/reviews/cerana/cerana/178#-KJMV7PvTcKSZzSreuBy:-KJMdnkJ9sh73jYOLYOO:160401916) ([raw file](https://github.com/cerana/cerana/blob/29d86a1f867df59ede6df04c14738a15fda4f0f7/providers/kv/mock.go#L16)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> When it was just a property, `Mock` did not satisfy the `provider.Provider` interface, as the methods didn't bubble up.
> </details>
> ahh

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/178)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[cmd/clusterconfig-provider/config.json, line 4 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo69Y4Waeh62DhokBB:-KJMauII6YtI7yDK0EE9:-1578463919) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/cmd/clusterconfig-provider/config.json#L4)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> doesn't seem like it. This should be a string like "6min" or w/e it is.
> </details>
> Could have sworn I did this. Must have gotten lost somewhere along the way. Updated these and created an issue #205 to go through and change all other TTL config options across the board accordingly.

---

_[providers/clusterconf/bundle.go, line 24 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo8EUaVPEz1JR3Tsyc:-KJMZHE7drJ7Hi96qSj8:846951927) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/providers/clusterconf/bundle.go#L24)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> Serials still isn't really explained
> </details>
> I'd prefer to clarify this in the statspusher request, since that's the one actually choosing the serial. There's a few options for the key here and that discussion fits better with the statspusher. I'll update the comment here before merging that other branch in.

---

_[providers/clusterconf/bundle.go, line 32 [r1]](https://reviewable.io:443/reviews/cerana/cerana/178#-KIo8LT6t7SNAtrNHy3g:-KJMZcZ7tgU6ztaWDd2U:-244317452) ([raw file](https://github.com/cerana/cerana/blob/3d1549094a6d2dd17c33b0f34bd22632b80ad52d/providers/clusterconf/bundle.go#L32)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> hmmm should definitely not be bare `int` since thats not guaranteed to be of a specific size. So might as well go with `uint64`
> </details>
> `uint64` it is. Updated tests as well.

---

_[providers/clusterconf/clusterconf_test.go, line 15 [r5]](https://reviewable.io:443/reviews/cerana/cerana/178#-KJME9SLfl0tmtu63d4q:-KJMYE7W9Wb0V1eUU8kw:-1728894048) ([raw file](https://github.com/cerana/cerana/blob/29d86a1f867df59ede6df04c14738a15fda4f0f7/providers/clusterconf/clusterconf_test.go#L15)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> why the rename?
> </details>
> Remnant of when i had both `providers/kv` and `pkg/kv` in here. Renamed to just`kv`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/178)_

**Comment by mmlb** [comment]
Reviewed 6 of 11 files at r6.
Review status: 24 of 28 files reviewed at latest revision, 3 unresolved discussions.

---

_[providers/clusterconf/bundle.go, line 150 [r6]](https://reviewable.io:443/reviews/cerana/cerana/178#-KJMfSgIrISE7d5ULH3F:-KJMfSgIrISE7d5ULH3G:2076948853) ([raw file](https://github.com/cerana/cerana/blob/d4666673c0f9a3b85bf9f7705a2b5320f1848e53/providers/clusterconf/bundle.go#L150)):_

> ``` Go
>   if args.Bundle.ID == 0 {
>       rand.Seed(time.Now().UnixNano())
>       args.Bundle.ID = uint64(rand.Uint32())
> ```

you want `uint64(rand.Int63())`

---

_[providers/clusterconf/bundle_test.go, line 25 [r6]](https://reviewable.io:443/reviews/cerana/cerana/178#-KJMfmfuW_lf9zbyVHKS:-KJMfmfuW_lf9zbyVHKT:-1373611591) ([raw file](https://github.com/cerana/cerana/blob/d4666673c0f9a3b85bf9f7705a2b5320f1848e53/providers/clusterconf/bundle_test.go#L25)):_

> ``` Go
>   }{
>       {"zero id", 0, make(map[string]net.IP), "missing arg: id"},
>       {"nonexistent id", uint64(rand.Uint32()), make(map[string]net.IP), "bundle config not found"},
> ```

ditto in all the other calls here

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/178)_

**Comment by mmlb** [comment]
Reviewed 1 of 14 files at r3, 4 of 11 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/178)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[providers/clusterconf/bundle.go, line 150 [r6]](https://reviewable.io:443/reviews/cerana/cerana/178#-KJMfSgIrISE7d5ULH3F:-KJMh0qSZufAS44d2--x:-499146009) ([raw file](https://github.com/cerana/cerana/blob/d4666673c0f9a3b85bf9f7705a2b5320f1848e53/providers/clusterconf/bundle.go#L150)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> you want `uint64(rand.Int63())`
> </details>
> Done.

---

_[providers/clusterconf/bundle_test.go, line 25 [r6]](https://reviewable.io:443/reviews/cerana/cerana/178#-KJMfmfuW_lf9zbyVHKS:-KJMh1uBL6UtoM2C0Vjk:-499146009) ([raw file](https://github.com/cerana/cerana/blob/d4666673c0f9a3b85bf9f7705a2b5320f1848e53/providers/clusterconf/bundle_test.go#L25)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> ditto in all the other calls here
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/178)_

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/178)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/kv/mock.go, line 16 [r5]](https://reviewable.io:443/reviews/cerana/cerana/178#-KJMV7PvTcKSZzSreuBy:-KJMho73rhw6o0YQ4SAK:-499146009) ([raw file](https://github.com/cerana/cerana/blob/29d86a1f867df59ede6df04c14738a15fda4f0f7/providers/kv/mock.go#L16)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> ahh
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/178)_

**Pull request merged**
