### PR TITLE
metrics provider

### LINKED ISSUE #51: Create System Stats/Metrics Provider
<a href="https://github.com/TauZero"></img></a> **Issue by [TauZero](https://github.com/TauZero)**
_Tue Mar 15 21:01:08 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/51_

---

Providing at the very least:
- Network activity
- CPU activity
- Disk usage
- Memory usage
- Running managed processes

Plus maybe some rollup method for querying multiples at once. Stub where necessary and create new cards to fill those in when dependencies are met.

### PR DESCRIPTION
**Pull request by bbickerton**
## Issues affected/resolved

(See https://github.com/blog/1506-closing-issues-via-pull-requests)
Resolves #51 
## Description:

Basic system  metrics and info

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/82)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 15 of 15 files at r1, 6 of 6 files at r2, 2 of 2 files at r3, 7 of 7 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[.gitignore, line 6 [r3]](https://reviewable.io:443/reviews/cerana/cerana/82#-KEfzThko4Eq8633ig_C:-KEfzThko4Eq8633ig_D:-586845021) ([raw file](https://github.com/cerana/cerana/blob/c5fb702245ca12a18c6083e885d241aba37633bb/.gitignore#L6)):_
yeah this commit should be squashed with the one that introduces the binary

---

_[cmd/metrics-provider/main.go, line 12 [r1]](https://reviewable.io:443/reviews/cerana/cerana/82#-KEfyGd_2fBe6M4q7beW:-KEfyGd_2fBe6M4q7beX:-632977206) ([raw file](https://github.com/cerana/cerana/blob/085742e1c7d8a1658c2b629d8b046cd25a3dec6a/cmd/metrics-provider/main.go#L12)):_
I wonder if we should just do this in logrusx's `init()` func and let bygones just be.

---

_[providers/metrics/disk.go, line 17 [r2]](https://reviewable.io:443/reviews/cerana/cerana/82#-KEfzDX_CdnhXJdPuPIc:-KEfzDX_CdnhXJdPuPId:-60688316) ([raw file](https://github.com/cerana/cerana/blob/3f363ac128e0680a508d7e6b8e89e431eb6a9941/providers/metrics/disk.go#L17)):_
what does `io` mean?

---

_[providers/metrics/hardware.go, line 15 [r5]](https://reviewable.io:443/reviews/cerana/cerana/82#-KEfzsuI2--0Zzt_4_MT:-KEfzsuJ4X_KP8uCWiYU:1529081731) ([raw file](https://github.com/cerana/cerana/blob/5f367a6789a3f8f9ad702495df4fefc8df7f6845/providers/metrics/hardware.go#L15)):_
I guess you can combine these two lines if you want.

---

_[providers/metrics/network.go, line 16 [r2]](https://reviewable.io:443/reviews/cerana/cerana/82#-KEfzMWjMe0n36xDelQ6:-KEfzMWjMe0n36xDelQ7:-109031860) ([raw file](https://github.com/cerana/cerana/blob/3f363ac128e0680a508d7e6b8e89e431eb6a9941/providers/metrics/network.go#L16)):_
ditto wrt `io` is this current usage or something?

---

_[cmd/metrics-provider/metrics-provider, line 0 [r1]](https://reviewable.io:443/reviews/cerana/cerana/82#-KEfz-6BWD6sl5X7R90k:-KEfz-6CIZQiGF8u1-NQ:-2104913633) ([raw file](https://github.com/cerana/cerana/blob/085742e1c7d8a1658c2b629d8b046cd25a3dec6a/cmd/metrics-provider/metrics-provider#L0)):_
can we rebase and get rid of this binary from history

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/82)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[.gitignore, line 6 [r3]](https://reviewable.io:443/reviews/cerana/cerana/82#-KEfzThko4Eq8633ig_C:-KEgXHWvII7GieaQGx8u:-499146009) ([raw file](https://github.com/cerana/cerana/blob/c5fb702245ca12a18c6083e885d241aba37633bb/.gitignore#L6)):_
Done.

---

_[cmd/metrics-provider/main.go, line 12 [r1]](https://reviewable.io:443/reviews/cerana/cerana/82#-KEfyGd_2fBe6M4q7beW:-KEgXNWqSzxUCInK0NKE:-476735129) ([raw file](https://github.com/cerana/cerana/blob/085742e1c7d8a1658c2b629d8b046cd25a3dec6a/cmd/metrics-provider/main.go#L12)):_
Mabye. There's plenty of places to change it (and/or make `logrusx` better), so better for a separate issue/PR.

---

_[providers/metrics/disk.go, line 17 [r2]](https://reviewable.io:443/reviews/cerana/cerana/82#-KEfzDX_CdnhXJdPuPIc:-KEgYbF-Vgf-3gZwsYDZ:358313951) ([raw file](https://github.com/cerana/cerana/blob/3f363ac128e0680a508d7e6b8e89e431eb6a9941/providers/metrics/disk.go#L17)):_
Things like bytes read/written, read/write times, read/write count.

---

_[providers/metrics/hardware.go, line 15 [r5]](https://reviewable.io:443/reviews/cerana/cerana/82#-KEfzsuI2--0Zzt_4_MT:-KEgY5gXy__3acW38i_v:-499146009) ([raw file](https://github.com/cerana/cerana/blob/5f367a6789a3f8f9ad702495df4fefc8df7f6845/providers/metrics/hardware.go#L15)):_
Done.

---

_[providers/metrics/network.go, line 16 [r2]](https://reviewable.io:443/reviews/cerana/cerana/82#-KEfzMWjMe0n36xDelQ6:-KEgYQWdlXBu9yEFrpuu:-1371284177) ([raw file](https://github.com/cerana/cerana/blob/3f363ac128e0680a508d7e6b8e89e431eb6a9941/providers/metrics/network.go#L16)):_
Things like bytes sent/received, packets sent/received.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/82)_

**Comment by bbickerton** [comment]
Review status: 7 of 17 files reviewed at latest revision, 6 unresolved discussions.

---

_[cmd/metrics-provider/metrics-provider, line  [r1]](https://reviewable.io:443/reviews/cerana/cerana/82#-KEfz-6BWD6sl5X7R90k:-KEg_Xv5tMjx3jxeztr2:-1069939555) ([raw file](https://github.com/cerana/cerana/blob/085742e1c7d8a1658c2b629d8b046cd25a3dec6a/cmd/metrics-provider/metrics-provider#L)):_
This seems to be gone after rebasing the gitignore into the first commit. I can't find the file in the history on my side.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/82)_

**Comment by mmlb** [comment]
Reviewed 10 of 10 files at r7, 6 of 6 files at r8, 7 of 7 files at r9, 2 of 2 files at r10, 1 of 1 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/82)_

**Pull request merged**
