### PR TITLE
Dhcp fixes

### PR DESCRIPTION
**Pull request by mmlb**
#### Description:

Decouple `cmd/dhcp-provider` from dependencies being up (including coordinator)

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/317)

### CODE REVIEW

**Comment by bbickerton** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[run-test.sh, line 38 [r1]](https://reviewable.io:443/reviews/cerana/cerana/317#-KOot82Wa7qjwGC8nWE8:-KOot82Wa7qjwGC8nWE9:b-6izd29) ([raw file](https://github.com/cerana/cerana/blob/c64de21826af0a26fba3a0f4e0559b752e829c8e/run-test.sh#L38)):_

> ``` Shell
> docker rm -v "$cid" > /dev/null || :
> echo "### TEST  $name"
> cat "$out"
> ```

I thought we removed the `cat $out` since it's being printed live? I'm still seeing double output with this.

---

_[cmd/dhcp-provider/main.go, line 38 [r2]](https://reviewable.io:443/reviews/cerana/cerana/317#-KOousce6kOqNJ-fAJg7:-KOouscfC52c5e4J2514:b-2fj8h0) ([raw file](https://github.com/cerana/cerana/blob/9422437759ba756c94b2db94da8e3195f3324013/cmd/dhcp-provider/main.go#L38)):_

> ``` Go
>       ErrorHandler:   handler,
>   })
>   dieOnError("create request object", err)
> ```

Why did these get changed back from `logrusx.DieOnError` to the local `dieOnError`?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/317)_

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[run-test.sh, line 38 [r1]](https://reviewable.io:443/reviews/cerana/cerana/317#-KOot82Wa7qjwGC8nWE8:-KOp40vLvXZlvZgtee0N:b-l5uujr) ([raw file](https://github.com/cerana/cerana/blob/c64de21826af0a26fba3a0f4e0559b752e829c8e/run-test.sh#L38)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> I thought we removed the `cat $out` since it's being printed live? I'm still seeing double output with this.
> </details>
> hmm yeah will do, wanted minimal changes at first and forgot to drop this

---

_[cmd/dhcp-provider/main.go, line 38 [r2]](https://reviewable.io:443/reviews/cerana/cerana/317#-KOousce6kOqNJ-fAJg7:-KOp4JrHmSQd1_9S2sQT:bs2bje7) ([raw file](https://github.com/cerana/cerana/blob/9422437759ba756c94b2db94da8e3195f3324013/cmd/dhcp-provider/main.go#L38)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Why did these get changed back from `logrusx.DieOnError` to the local `dieOnError`?
> </details>
> bad merge will fix

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/317)_

**Comment by mmlb** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[cmd/dhcp-provider/main.go, line 38 [r2]](https://reviewable.io:443/reviews/cerana/cerana/317#-KOousce6kOqNJ-fAJg7:-KOqE0xhTA8W3nBMOMSB:b-896fix) ([raw file](https://github.com/cerana/cerana/blob/9422437759ba756c94b2db94da8e3195f3324013/cmd/dhcp-provider/main.go#L38)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> bad merge will fix
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/317)_

**Comment by bbickerton** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/317)_

**Comment by bbickerton** [comment]
Reviewed 1 of 3 files at r4.
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/317)_

**Comment by bbickerton** [comment]
Reviewed 1 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/317)_

**Comment by bbickerton** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/317)_

**Comment by bbickerton** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/317)_

**Pull request merged**
