### PR TITLE
Hotfix to realfix

### LINKED ISSUE #309: Demo Hotfixes to RealFixes
#### Issue Description

Review commits from the `demotick`, `systemd_nspawn`, and `demo_hotfixes` branches. Organize and decide which need to become full features / fixes. Make equivalent production-ready changes based off master.
#### Acceptance Criteria (how do we know when this is done?)

Demo can be run successfully without `demo_hotfixes` branch.
Commits in `demotick` branch are solely related to the demotick binary
Commits in `systemd_nspawn` branch are solely related to the use of systemd_nspawn

### PR DESCRIPTION
**Pull request by bbickerton**
#### Description:

Convert the set of demo-driven hotfixes to production ready changes.
#### Issues affected:

Resolves #309

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/310)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

_[acomm/tracker.go, line 508 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBcIU3_Vy4bxm2dvYF:-KOBcIU3_Vy4bxm2dvYG:1908575746) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/acomm/tracker.go#L508)):_

> ``` Go
>   }
> 
>   r, err := regexp.Compile("^(|localhost|127.0.0.1)$")
> ```

4 things
1 empty first alternative
2 should match against any ip in 127.\* range
3 `::1` isn't actually being handled right?
4 should we be compiling the regex every time? Why not just have it as a global var?

this should probably be

```
`^(localhost|127(?:\.\d{1,3}){3})$`
```

---

_[acomm/tracker_test.go, line 241 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBiTiXerU_fqcF5nBK:-KOBiTiXerU_fqcF5nBL:272744618) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/acomm/tracker_test.go#L241)):_

> ``` Go
>       {"http://127.0.0.1/path", "foobar:8080", "http://foobar/path"},
>       {"http://127.0.0.1:8080/path", "foobar", "http://foobar:8080/path"},
>       {"http://127.0.0.1:8080/path", "foobar:1234", "http://foobar:8080/path"},
> ```

missing tests for non-`127.0.0.1` ipv4 localhosts
missing tests for ipv6 (since it's mentioned in the docs for the func)

---

_[cmd/statspusher/dataset.go, line 139 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBlm0kUgSKxPwfOLB9:-KOBlm0l8AnWtlKsVjjh:-997202177) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/cmd/statspusher/dataset.go#L139)):_

> ``` Go
>   for _, iface := range data.Interfaces {
>       for _, ifaceAddr := range iface.Addrs {
>           ip, _, err := net.ParseCIDR(ifaceAddr.Addr)
> ```

hmm this looks pretty odd. I wouldn't ever expect to be able to parse both CIDR and IP in the same function, they mean totally different things. Whatever is setting up data.Interfaces should  probably be fixed instead.

---

_[providers/clusterconf/bundle.go, line 240 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBowU-oywbYZNyMyPF:-KOBowU0AT1I-RkeZO3G:756047212) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/providers/clusterconf/bundle.go#L240)):_

> ``` Go
>       // e.g. {prefix}/{id}/{rest/of/path}
>       var id uint64
>       _, err := fmt.Sscanf(key, filepath.Join(bundlesPrefix, "%d"), &id)
> ```

hmm IDK if go is smart enough to pull out the filepath.Join out of the loop, though I would expect the SSA backend to do so. I'd move it out since IMO its clearer that the format argument isn't changing.

---

_[providers/clusterconf/bundle.go, line 249 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBnttrLKSPsx9VBhGV:-KOBnttrLKSPsx9VBhGW:1040571512) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/providers/clusterconf/bundle.go#L249)):_

> ``` Go
>   var wg sync.WaitGroup
>   bundleChan := make(chan *Bundle, len(ids))
>   errChan := make(chan error, len(ids))
> ```

these 2 channels are going to grow huge once we have a non-trivial amount of bundles. This is definitely going to need to be reworked soonish.

---

_[providers/clusterconf/dataset.go, line 72 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBoQxZBzYmhmwN_6Ep:-KOBoQxZBzYmhmwN_6Eq:-469765787) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/providers/clusterconf/dataset.go#L72)):_

> ``` Go
>       // e.g. {prefix}/{id}/{rest/of/path}
>       var id string
>       _, err := fmt.Sscanf(key, filepath.Join(datasetsPrefix, "%s"), &id)
> ```

ditto

---

_[providers/clusterconf/dataset.go, line 81 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBoCKqrmY7hUh8U6Nx:-KOBoCKqrmY7hUh8U6Ny:1452542218) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/providers/clusterconf/dataset.go#L81)):_

> ``` Go
>   var wg sync.WaitGroup
>   dsChan := make(chan *Dataset, len(ids))
>   errChan := make(chan error, len(ids))
> ```

same comment as in `ListBundles`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/310)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

_[acomm/tracker.go, line 508 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBcIU3_Vy4bxm2dvYF:-KOC0UrdiMvlrpyyKL2w:-1594172233) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/acomm/tracker.go#L508)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> 4 things
> 1 empty first alternative
> 2 should match against any ip in 127.\* range
> 3 `::1` isn't actually being handled right?
> 4 should we be compiling the regex every time? Why not just have it as a global var?
> 
> this should probably be
> 
> ```
> `^(localhost|127(?:\.\d{1,3}){3})$`
> ```
> 
> </details>
> 1. That was intentional. Go's `http` treats empty as an implict localhost
> 2. Ok
> 3. Forgot to add it to the regex
> 4. Pulled out to a global with a value based on your suggested regex plus the empty first alternative (implicit localhost) plus ipv6 ::1

---

_[acomm/tracker_test.go, line 241 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBiTiXerU_fqcF5nBK:-KOC424FgfAXwv3eeLiu:-499146009) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/acomm/tracker_test.go#L241)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> missing tests for non-`127.0.0.1` ipv4 localhosts
> missing tests for ipv6 (since it's mentioned in the docs for the func)
> </details>
> Done.

---

_[cmd/statspusher/dataset.go, line 139 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBlm0kUgSKxPwfOLB9:-KOC5M9k7C8biIoqrKJ4:2143738066) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/cmd/statspusher/dataset.go#L139)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> hmm this looks pretty odd. I wouldn't ever expect to be able to parse both CIDR and IP in the same function, they mean totally different things. Whatever is setting up data.Interfaces should  probably be fixed instead.
> </details>
> It's coming from https://godoc.org/github.com/shirou/gopsutil/net#InterfaceStat , which I think is using https://github.com/shirou/gopsutil/blob/master/net/net_linux.go#L453 at least on linux. I thought I saw it come back as a regular IP when first writing this stuff, but it came back as a CIDR during the demo. Someone suggested stripping off everything after a `/` and parsing it as an IP, which made it seem like handling either would be fine.

---

_[providers/clusterconf/bundle.go, line 240 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBowU-oywbYZNyMyPF:-KOC6LsY3PnZgRiG4SRa:-499146009) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/providers/clusterconf/bundle.go#L240)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> hmm IDK if go is smart enough to pull out the filepath.Join out of the loop, though I would expect the SSA backend to do so. I'd move it out since IMO its clearer that the format argument isn't changing.
> </details>
> Done.

---

_[providers/clusterconf/bundle.go, line 249 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBnttrLKSPsx9VBhGV:-KOC6eCqZ5SJWDzOwy0e:1085254580) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/providers/clusterconf/bundle.go#L249)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> these 2 channels are going to grow huge once we have a non-trivial amount of bundles. This is definitely going to need to be reworked soonish.
> </details>
> What do you consider huge / non-trivial and what exactly is the problem you want to avoid?

---

_[providers/clusterconf/dataset.go, line 72 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBoQxZBzYmhmwN_6Ep:-KOC6L8Mb_iykk_LdutW:-499146009) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/providers/clusterconf/dataset.go#L72)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> ditto
> </details>
> Done.

---

_[providers/clusterconf/dataset.go, line 81 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBoCKqrmY7hUh8U6Nx:-KOC6mpqx1hn8mvdr2iL:1345196477) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/providers/clusterconf/dataset.go#L81)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> same comment as in `ListBundles`
> </details>
> We'll discuss above.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/310)_

**Comment by mmlb** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

_[acomm/tracker_test.go, line 241 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBiTiXerU_fqcF5nBK:-KOH-2t6CKBfXk1PeDWH:-1716419165) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/acomm/tracker_test.go#L241)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Done.
> </details>
> I meant adding  tests for ips like 127.42.42.42... the 108 stuff is good, lets keep them but lets also verify that 127/8 works as localhost.

---

_[cmd/statspusher/dataset.go, line 139 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBlm0kUgSKxPwfOLB9:-KOH030th0RHYIc1AYdu:-585116436) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/cmd/statspusher/dataset.go#L139)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> It's coming from https://godoc.org/github.com/shirou/gopsutil/net#InterfaceStat , which I think is using https://github.com/shirou/gopsutil/blob/master/net/net_linux.go#L453 at least on linux. I thought I saw it come back as a regular IP when first writing this stuff, but it came back as a CIDR during the demo. Someone suggested stripping off everything after a `/` and parsing it as an IP, which made it seem like handling either would be fine.
> </details>
> hmmm following the code I get (assuming that `data.Interfaces` come from `gopsutil.Interfaces()` at some):

gopsutil.Interfaces() -> net.Interfaces() -> net.interfaceTable(0) -> platform_specific_fetch_of_interfaces
then for each interface gopsutils populates InterfaceStat.Addrs by
net.Interface.Addrs()  which in interfaces_{linux,bsd(includes darwin),windows} always builds an net.IPNet so I think ParseCIDR should be the only thing used...

I wonder if gopsutil used to use some other method to get ip address before?

---

_[providers/clusterconf/bundle.go, line 237 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOH7eXZv7O4poKwXw7F:-KOH7eXZv7O4poKwXw7G:-851250902) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/providers/clusterconf/bundle.go#L237)):_

> ``` Go
>   ids := make(map[uint64]bool)
>   for _, key := range keys {
>       // keys are full paths and include all child keys.
> ```

fyi this sounds wrong, I am expecting (from memory) for `kv.Keys("some/path")` to only list the direct children of `some/path`. I'll go back and check up on this tomorrow probably.

---

_[providers/clusterconf/bundle.go, line 249 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBnttrLKSPsx9VBhGV:-KOH6ZY3Igzn237OIAjn:2146859811) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/providers/clusterconf/bundle.go#L249)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> What do you consider huge / non-trivial and what exactly is the problem you want to avoid?
> </details>
> hmm well I was worried about enumerating and building up a list of bundles taking a long time and consuming a bunch of ram for very short amount of time when we have lots of bundles. It would be great if we could stream the values to receiver so that only it needs to build up the full list in ram. But this is an issue for another day I guess.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/310)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

_[acomm/tracker_test.go, line 241 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBiTiXerU_fqcF5nBK:-KOLp_5GsRn_Y4_LGaVE:1895757379) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/acomm/tracker_test.go#L241)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> I meant adding  tests for ips like 127.42.42.42... the 108 stuff is good, lets keep them but lets also verify that 127/8 works as localhost.
> </details>
> Done. Also added more ipv6 related tests and substitutions.

---

_[cmd/statspusher/dataset.go, line 139 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOBlm0kUgSKxPwfOLB9:-KOLrtiE_JIEgBf133ux:1073556655) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/cmd/statspusher/dataset.go#L139)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> hmmm following the code I get (assuming that `data.Interfaces` come from `gopsutil.Interfaces()` at some):
> 
> gopsutil.Interfaces() -> net.Interfaces() -> net.interfaceTable(0) -> platform_specific_fetch_of_interfaces
> then for each interface gopsutils populates InterfaceStat.Addrs by
> net.Interface.Addrs()  which in interfaces_{linux,bsd(includes darwin),windows} always builds an net.IPNet so I think ParseCIDR should be the only thing used...
> 
> I wonder if gopsutil used to use some other method to get ip address before?
> </details>
> Switched to `net.ParseCIDR` only.

---

_[providers/clusterconf/bundle.go, line 237 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOH7eXZv7O4poKwXw7F:-KOLtKpmPStcNZKeNhih:-832962782) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/providers/clusterconf/bundle.go#L237)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> fyi this sounds wrong, I am expecting (from memory) for `kv.Keys("some/path")` to only list the direct children of `some/path`. I'll go back and check up on this tomorrow probably.
> </details>
> Unless your `kv` is doing some trimming, this is the case. Using `consul` directly:
> 
> ```
> $ curl -XGET --url "http://localhost:8500/v1/kv/?keys"
> ["bang/asdf/bar4","bang/bar","bang/bar2","bang/bar3","foo/asdf/bar4","foo/bar","foo/bar2","foo/bar3"]
> ```

$ curl -XGET --url "http://localhost:8500/v1/kv/foo?keys"
["foo/asdf/bar4","foo/bar","foo/bar2","foo/bar3"]

$ curl -XGET --url "http://localhost:8500/v1/kv/bang?keys"
["bang/asdf/bar4","bang/bar","bang/bar2","bang/bar3"]

$ curl -XGET --url "http://localhost:8500/v1/kv/foo/asdf?keys"
["foo/asdf/bar4"]

```

The keys lookup is basically "all keys with containing specified prefix".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/310)*
<!-- Sent from Reviewable.io -->
```

**Comment by mmlb** [comment]
Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[providers/clusterconf/bundle.go, line 237 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOH7eXZv7O4poKwXw7F:-KOPdQPw05N7eYc5bmOi:b-ix384h) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/providers/clusterconf/bundle.go#L237)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Unless your `kv` is doing some trimming, this is the case. Using `consul` directly:
> 
> ```
> $ curl -XGET --url "http://localhost:8500/v1/kv/?keys"
> ["bang/asdf/bar4","bang/bar","bang/bar2","bang/bar3","foo/asdf/bar4","foo/bar","foo/bar2","foo/bar3"]
> 
> $ curl -XGET --url "http://localhost:8500/v1/kv/foo?keys"
> ["foo/asdf/bar4","foo/bar","foo/bar2","foo/bar3"]
> 
> $ curl -XGET --url "http://localhost:8500/v1/kv/bang?keys"
> ["bang/asdf/bar4","bang/bar","bang/bar2","bang/bar3"]
> 
> $ curl -XGET --url "http://localhost:8500/v1/kv/foo/asdf?keys"
> ["foo/asdf/bar4"]
> ```
> 
> The keys lookup is basically "all keys with containing specified prefix".
> </details>
> not quite, I should be adding the separator option to get:
> 
> ```
> curl -XGET 'localhost:8500/v1/kv/test/?keys'; echo; curl -XGET 'localhost:8500/v1/kv/test/?keys&separator=/'
> ￼["test/bar/bar","test/baz/baz","test/foo/foo"]
> ["test/bar/","test/baz/","test/foo/"]
> ```
> 
> see https://github.com/cerana/cerana/blob/master/pkg/kv/consul/consul.go#L94
> and the test for it too
> https://github.com/cerana/cerana/blob/master/pkg/kv/kv_test.go#L215
> which get set here
> https://github.com/cerana/cerana/blob/master/pkg/kv/kv_test.go#L42

maybe this is a holdover from before kv was ready, can you try without it?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/310)_

**Comment by bbickerton** [comment]
Review status: 27 of 29 files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/clusterconf/bundle.go, line 237 [r1]](https://reviewable.io:443/reviews/cerana/cerana/310#-KOH7eXZv7O4poKwXw7F:-KOQh_DJl-xyO1UiNU4-:b-k1jkmz) ([raw file](https://github.com/cerana/cerana/blob/c28e999bb0409ce5d6e57af2188c5f02205b7eb6/providers/clusterconf/bundle.go#L237)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> not quite, I should be adding the separator option to get:
> 
> ```
> curl -XGET 'localhost:8500/v1/kv/test/?keys'; echo; curl -XGET 'localhost:8500/v1/kv/test/?keys&separator=/'
> ￼["test/bar/bar","test/baz/baz","test/foo/foo"]
> ["test/bar/","test/baz/","test/foo/"]
> ```
> 
> see https://github.com/cerana/cerana/blob/master/pkg/kv/consul/consul.go#L94
> and the test for it too
> https://github.com/cerana/cerana/blob/master/pkg/kv/kv_test.go#L215
> which get set here
> https://github.com/cerana/cerana/blob/master/pkg/kv/kv_test.go#L42
> 
> maybe this is a holdover from before kv was ready, can you try without it?
> </details>
> Tested and you're right. Probably a holdover. Parsing should be the same with Sscanf, so I've just removed the erroneous comment from here and datasets.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/310)_

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/310)_

**Pull request merged**
