### PR TITLE
Travis tweaks v2

### PR DESCRIPTION
**Pull request by mmlb**
#### Description:

use `glide install`
update vendored `go-zfs`
drop go 1.5 from travis and add tip.
fix a go vet error when running under tip
#### Issues affected:

tests for #233

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/240)

### CODE REVIEW

**Comment by bbickerton** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[.travis.yml, line 31 [r1]](https://reviewable.io:443/reviews/cerana/cerana/241#-KKtN5fmL2qFa2nFN2JN:-KKtN5fmL2qFa2nFN2JO:-1181628948) ([raw file](https://github.com/cerana/cerana/blob/837f1192ed452c73c515097862027ac1c418e149/.travis.yml#L31)):_

> ``` YAML
>   - mkdir -p $ZFS_CACHE
>   - .travis/deps.sh fetch
>   - glide install
> ```

Does travis come with glide preinstalled or does this need to be added to deps.sh?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/241)_

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[.travis.yml, line 31 [r1]](https://reviewable.io:443/reviews/cerana/cerana/241#-KKtN5fmL2qFa2nFN2JN:-KKtP0DNJw-q2tAo5Dj8:278916795) ([raw file](https://github.com/cerana/cerana/blob/837f1192ed452c73c515097862027ac1c418e149/.travis.yml#L31)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> Does travis come with glide preinstalled or does this need to be added to deps.sh?
> </details>
> get out of here with you rational comments.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/241)_

**Comment by mmlb** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

_[.travis.yml, line 31 [r1]](https://reviewable.io:443/reviews/cerana/cerana/241#-KKtN5fmL2qFa2nFN2JN:-KKyEdmbmjcB0g5bmwc4:-499146009) ([raw file](https://github.com/cerana/cerana/blob/837f1192ed452c73c515097862027ac1c418e149/.travis.yml#L31)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> get out of here with you rational comments.
> </details>
> Done.

---

_[glide.yaml, line 6 [r2]](https://reviewable.io:443/reviews/cerana/cerana/241#-KKyEvXqT0SvOAkiGgNM:-KKyEvXqT0SvOAkiGgNN:1401114978) ([raw file](https://github.com/cerana/cerana/blob/b9edbefec82a21a659a5d47a1005977c902ad469/glide.yaml#L6)):_

> ``` YAML
>   version: ^0.10.0
> - package: github.com/coreos/etcd
>   version: ~2.1.1
> ```

fyi this just means take any patch level updates (which we should see none of). I changed it so that it matches what we had back in mistify.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/241)_

**Comment by bbickerton** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/241)_

**Comment by bbickerton** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/241)_

**Pull request merged**
