### PR TITLE
187 boot time config

### LINKED ISSUE #187: Implement Boot-time Config in Cerana
## Issue Description

@daleghent started a bulk of the work on a boot-time config menu in #63 . The purpose of this task is to take that work and implement in Cerana.  It is likely this will turn into an epic and spawn additional cards.

Both @nshalman and @StevenIsaacs  will be attacking this jointly until it is complete or additional tasks are spawned and assigned.

### PR DESCRIPTION
**Pull request by nshalman**
#### Description:

This is all the boot time tooling, some accompanying documentation, and some tools for the build system including some testing tools by @StevenIsaacs.

Basically, code under boot/ and documentation under docs/ is mostly work done by me, code under build/ is work done by @StevenIsaacs.

This is the branch we are currently using for builds, so it's past time for this stuff to land in master (so that people can more easily merge master into a development branch and then use Nix to build their test branch.)

Code under boot/ has been formatted with shfmt and checked with ShellCheck.
#### Issues affected:

Resolves #187

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/265)

### CODE REVIEW

**Comment by joshie** [comment]
lgtm as long as working

**Comment by mmlb** [comment]
Review status: 0 of 18 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

_[boot/Makefile, line 10 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAccDVFco-dwYtydPM:-KMAccDVFco-dwYtydPN:-252409525) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/Makefile#L10)):_

> ``` Makefile
>   mkdir -p $(DESTDIR)/scripts/
>   cp $? $(DESTDIR)/scripts/
>   chmod +x $(DESTDIR)/scripts/*
> ```

lines can be collapsed down to:

```
install -Dm755 -t DESTDDIR/scripts $?
```

---

_[boot/scripts/copy-platform.sh, line 16 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAf5Nw0exYAy1AMyq7:-KMAf5Nw0exYAy1AMyq8:-295924986) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/copy-platform.sh#L16)):_

> ``` Shell
>     ln -s bootcd /data/platform/current
>     # No physical media, most likely PXE booted
>     # FIXME
> ```

do we have an issue for this?

---

_[boot/scripts/gen-hostid.sh, line 8 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAfLxI117FiLzk5smf:-KMAfLxI117FiLzk5smg:-577685325) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/gen-hostid.sh#L8)):_

> ``` Shell
> 
> if [ -f $uuid_file ]; then
>     uuid=$(tr '[:upper:]' '[:lower:]' <"$uuid_file")
> ```

remove `"`s or add to `if` test for consistency

---

_[boot/scripts/gen-hostid.sh, line 21 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAfgVmV85c5JU8EL5w:-KMAfgVmV85c5JU8EL5x:-1323160084) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/gen-hostid.sh#L21)):_

> ``` Shell
> d=${host_id:0:2}
> 
> echo -ne "\\x$a\\x$b\\x$c\\x$d" >/etc/hostid \
> ```

I've never understood the ordering here, istm it should be backwards. `Setting` implies future action and if it fails we won't know why. minor though...

---

_[boot/scripts/init-zpools.sh, line 27 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAgRottl1jr16PnyWF:-KMAgRottl1jr16PnyWG:-1734864060) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/init-zpools.sh#L27)):_

> ``` Shell
>     done
> 
>     if [[ "off" = $(zfs get compression -Ho value $ZPOOL) ]]; then zfs set compression=lz4 $ZPOOL; fi
> ```

should be multiple lines

---

_[boot/scripts/init-zpools.sh, line 105 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAgtwLcT0br4UESDW_:-KMAgtwM5_QvuSdYTB_0:-1959781918) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/init-zpools.sh#L105)):_

> ``` Shell
> 
>     case $answer in
>         'auto')
> ```

This isn't presented anywhere to the user.

---

_[boot/scripts/init-zpools.sh, line 219 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAhS6o4i81WwYzgtWd:-KMAhS6o4i81WwYzgtWe:-351540180) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/init-zpools.sh#L219)):_

> ``` Shell
>     done
> 
>     # Block until Linux figures itself out w.r.t. paritions
> ```

sgdisk will not inform the kernel of partition changes (from http://www.rodsbooks.com/gdisk/sgdisk-walkthrough.html `Note, however, that the Linux kernel sometimes continues to use the old partition table after you've made changes.`) so `udevadm settle` seems like of little use. We could do `partprobe $disk` which scans/updates the kernel, but it's not part of the image.

---

_[boot/scripts/net-init.sh, line 61 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAkHgzd3Aw0tguM_Tw:-KMAkHh-tTFe-W3m5zo2:793982682) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/net-init.sh#L61)):_

> ``` Shell
>     local stat=1
> 
>     if [[ $prefix =~ ^[0-9]{1,2}$ ]]; then
> ```

`(( $prefix >= 8 && $prefix <= 32 ))` is better (imo)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/265)_

**Comment by mmlb** [comment]
Reviewed 6 of 15 files at r3, 1 of 8 files at r4, 1 of 1 files at r5, 10 of 12 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/265)_

**Comment by mmlb** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

_[boot/scripts/net-init.sh, line 159 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAqnTKPqrI6zClA2H-:-KMAlc-OkpJGa8SC7XKS:-1879947107) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/net-init.sh#L159)):_

> ``` Shell
>     esac
>     echo '"data_dir": "/data/config/consul/"' >>$CONFIG
>     echo '}' >>$CONFIG
> ```

This looks cleaner and is less lines too!

``` sh
 python > $CONFIG <<EOF
import json
d = {'server':True, 'data_dir': '/data/config/consul'}
if '$1' == "bootstrap":
        d['bootstrap'] = True
elif '$1' == 'join':
        d['start_join'] = '$CERANA_CLUSTER_IPS'.split(',')
else:
        import os
        print('unknown mode: $1')
        os.exit(1)
print(json.dumps(d))
EOF
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/265)_

**Comment by nshalman** [comment]
Review status: 16 of 18 files reviewed at latest revision, 9 unresolved discussions.

---

_[boot/Makefile, line 10 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAccDVFco-dwYtydPM:-KMAsNshm_k9sWczViHY:-499146009) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/Makefile#L10)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> lines can be collapsed down to:
> 
> ```
> install -Dm755 -t DESTDDIR/scripts $?
> ```
> 
> </details>
> Done.

---

_[boot/scripts/copy-platform.sh, line 16 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAf5Nw0exYAy1AMyq7:-KMAsPNwy-3nhwQdXPKt:-378937980) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/copy-platform.sh#L16)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> do we have an issue for this?
> </details>
> added into comment

---

_[boot/scripts/gen-hostid.sh, line 8 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAfLxI117FiLzk5smf:-KMAsX8Ce21IJ5aNGGhe:-499146009) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/gen-hostid.sh#L8)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> remove `"`s or add to `if` test for consistency
> </details>
> Done.

---

_[boot/scripts/gen-hostid.sh, line 21 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAfgVmV85c5JU8EL5w:-KMAsZE8AUxX5WGiNxLs:-499146009) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/gen-hostid.sh#L21)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> I've never understood the ordering here, istm it should be backwards. `Setting` implies future action and if it fails we won't know why. minor though...
> </details>
> Done.

---

_[boot/scripts/init-zpools.sh, line 27 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAgRottl1jr16PnyWF:-KMB-H5EDQLc_MKQDirr:-499146009) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/init-zpools.sh#L27)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> should be multiple lines
> </details>
> Done.

---

_[boot/scripts/init-zpools.sh, line 105 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAgtwLcT0br4UESDW_:-KMB-IDjzRyBXqoTwik1:-499146009) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/init-zpools.sh#L105)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> This isn't presented anywhere to the user.
> </details>
> Done.

---

_[boot/scripts/init-zpools.sh, line 219 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAhS6o4i81WwYzgtWd:-KMB-IodYx9QziqEtOyE:1740281843) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/init-zpools.sh#L219)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> sgdisk will not inform the kernel of partition changes (from http://www.rodsbooks.com/gdisk/sgdisk-walkthrough.html `Note, however, that the Linux kernel sometimes continues to use the old partition table after you've made changes.`) so `udevadm settle` seems like of little use. We could do `partprobe $disk` which scans/updates the kernel, but it's not part of the image.
> </details>
> Removed.

---

_[boot/scripts/net-init.sh, line 61 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAkHgzd3Aw0tguM_Tw:-KMB-KVRuNcPXjZCCsWU:1872707266) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/net-init.sh#L61)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> `(( $prefix >= 8 && $prefix <= 32 ))` is better (imo)
> </details>
> Fixed up.

---

_[boot/scripts/net-init.sh, line 159 [r6]](https://reviewable.io:443/reviews/cerana/cerana/265#-KMAqnTKPqrI6zClA2H-:-KMB-M_NSgl5FXn5s0Vy:-549641424) ([raw file](https://github.com/cerana/cerana/blob/98990782782dc062c49de0be8a3b47f77f91d6c8/boot/scripts/net-init.sh#L159)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> This looks cleaner and is less lines too!
> 
> ``` sh
>  python > $CONFIG <<EOF
> import json
> d = {'server':True, 'data_dir': '/data/config/consul'}
> if '$1' == "bootstrap":
>         d['bootstrap'] = True
> elif '$1' == 'join':
>         d['start_join'] = '$CERANA_CLUSTER_IPS'.split(',')
> else:
>         import os
>         print('unknown mode: $1')
>         os.exit(1)
> print(json.dumps(d))
> EOF
> ```
> 
> </details>
> No bringing python into the dependency chain... sorry.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/265)_

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/265)_

**Pull request merged**
