### PR TITLE
improve the build container experience

### PR DESCRIPTION
**Pull request by nshalman**
#### Description:

Adds some niceties to the build container and update the documentation

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/279)

### CODE REVIEW

**Comment by bbickerton** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/279)_

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/279)_

**Comment by trisk** [comment]
_[boot/bin/create-build-container, line 26 [r1]](https://reviewable.io:443/reviews/cerana/cerana/279#-KMjMTbSTAF4bbc0ynEC:-KMjMTbSTAF4bbc0ynED:-776079111) ([raw file](https://github.com/cerana/cerana/blob/101ea57300c6042848becbb5b84b53bf309ce287/boot/bin/create-build-container#L26)):_

> ```
> umount mnt/iso
> rm -r mnt/
> INIT=$(find nix -type f -path '*nixos*/init')
> ```

any way to just resolve the nix store path once instead of all the separate `find`s?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/279)_

**Comment by nshalman** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[boot/bin/create-build-container, line 26 [r1]](https://reviewable.io:443/reviews/cerana/cerana/279#-KMjMTbSTAF4bbc0ynEC:-KMjMhAkPBWSpLw1gU_1:189136479) ([raw file](https://github.com/cerana/cerana/blob/101ea57300c6042848becbb5b84b53bf309ce287/boot/bin/create-build-container#L26)):_
<details><summary>

<i>Previously, trisk (Albert Lee) wrote…</i></summary>



> any way to just resolve the nix store path once instead of all the separate `find`s?
> </details>
> No, each one is sitting in a different directory in the nix store:
> 
> ```
> ++ find nix -type f -path '*nixos*/init'
> + INIT=nix/store/h0pmin43nljip6x982isqzms30l1mhy9-nixos-system-nixos-16.03.1083.d745044/init
> ++ find nix -type f -path '*/bin/bash'
> ++ tail -n 1
> + BASH=nix/store/i7hx6w6zy3bv53f2xm1r23ya8qbzn4is-bash-4.3-p42/bin/bash
> ++ find nix -type f -path '*coreutils*/bin/env'
> + ENV=nix/store/w8vzn0lsahbd9sfh0v30x65qwq6xrpa8-coreutils-8.25/bin/env
> ++ find nix -type f -path '*net-tools*/bin/hostname'
> + HOSTNAME=nix/store/ifv0zv3fa1m09s0hcizwm4p39vlsmbps-net-tools-1.60_p20120127084908/bin/hostname
> ++ find nix/store/ -type f -path '*-local-cmds'
> + LOCAL=nix/store/5lm25rqvh0qf9q0nx86kq3dvhqfhmcbn-local-cmds
> ```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/279)_

**Comment by trisk** [comment]
_[boot/bin/create-build-container, line 26 [r1]](https://reviewable.io:443/reviews/cerana/cerana/279#-KMjMTbSTAF4bbc0ynEC:-KMjXCjulwcJTHWDeOaE:-1676546613) ([raw file](https://github.com/cerana/cerana/blob/101ea57300c6042848becbb5b84b53bf309ce287/boot/bin/create-build-container#L26)):_
<details><summary>

<i>Previously, nshalman (Nahum Shalman) wrote…</i></summary>



> No, each one is sitting in a different directory in the nix store:
> 
> ```
> ++ find nix -type f -path '*nixos*/init'
> + INIT=nix/store/h0pmin43nljip6x982isqzms30l1mhy9-nixos-system-nixos-16.03.1083.d745044/init
> ++ find nix -type f -path '*/bin/bash'
> ++ tail -n 1
> + BASH=nix/store/i7hx6w6zy3bv53f2xm1r23ya8qbzn4is-bash-4.3-p42/bin/bash
> ++ find nix -type f -path '*coreutils*/bin/env'
> + ENV=nix/store/w8vzn0lsahbd9sfh0v30x65qwq6xrpa8-coreutils-8.25/bin/env
> ++ find nix -type f -path '*net-tools*/bin/hostname'
> + HOSTNAME=nix/store/ifv0zv3fa1m09s0hcizwm4p39vlsmbps-net-tools-1.60_p20120127084908/bin/hostname
> ++ find nix/store/ -type f -path '*-local-cmds'
> + LOCAL=nix/store/5lm25rqvh0qf9q0nx86kq3dvhqfhmcbn-local-cmds
> ```
> 
> </details>
> OK, this is fine.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/279)_

**Comment by trisk** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/279)_

**Pull request merged**
