### PR TITLE
Statpusher comms

### LINKED ISSUE #235: Statspusher talk directly to both L1 and L2 coordinators
#### Issue Description

Right now it's set up with L1 as the coordinator URL and L2 as the taskURL for setting heartbeats, resulting in `statspusher->L1->provider` for info and `statspusher->L1->L2->clusterconf-provider` for heartbeats. There was a misunderstanding at what layer `statspusher` is categorized.

Make it so that:
`statspusher -> L1 coordinator -> provider` for data
`statspusher -> L1 coordinator -> provider` for heartbeat

### PR DESCRIPTION
**Pull request by bbickerton**
#### Description:

Rework the `statspusher` to communicate directly with the L1/node coordinator and the L2/cluster coordinator
#### Issues affected:

Resolves #235

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/238)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 8 of 8 files at r1, 6 of 6 files at r2, 8 of 8 files at r3, 3 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[cmd/statspusher/config.go, line 66 [r2]](https://reviewable.io:443/reviews/cerana/cerana/238#-KKyPrduK92BHfaE1B8w:-KKyPrduK92BHfaE1B8x:836518729) ([raw file](https://github.com/cerana/cerana/blob/a53c68702cac9e6b2c6e9ec3a1b82dcd8e333fa0/cmd/statspusher/config.go#L66)):_

> ``` Go
>   flagSet.StringP("logLevel", "l", "warning", "log level: debug/info/warn/error/fatal/panic")
>   flagSet.Uint64P("requestTimeout", "r", 0, "default timeout for requests made (seconds)")
>   flagSet.Uint64P("datasetInterval", "d", 0, "dataset heartbeat interval (seconds)")
> ```

can use `flagSet.Duration`. Is there a card for updating all cli duration args to time.Duration?

---

_[cmd/statspusher/config.go, line 178 [r2]](https://reviewable.io:443/reviews/cerana/cerana/238#-KKyQ6B0Oee9njeWT9SH:-KKyQ6B0Oee9njeWT9SI:795021459) ([raw file](https://github.com/cerana/cerana/blob/a53c68702cac9e6b2c6e9ec3a1b82dcd8e333fa0/cmd/statspusher/config.go#L178)):_

> ``` Go
> 
> func (c *config) validate() error {
>   if c.datasetInterval() <= 0 {
> ```

should be `== 0` since uint64s will never be `< 0`

---

_[cmd/statspusher/config.go, line 141 [r3]](https://reviewable.io:443/reviews/cerana/cerana/238#-KKypFhgil5K6wm5w9RR:-KKypFhgil5K6wm5w9RS:605829835) ([raw file](https://github.com/cerana/cerana/blob/9f45ee3e4ac6a8e96634e67b8cc3259e0d43625c/cmd/statspusher/config.go#L141)):_

> ``` Go
> func (c *config) clusterDataURL() *url.URL {
>   // Error checking has been done during validation
>   u, _ := url.ParseRequestURI(c.viper.GetString("clusterDataURL"))
> ```

if that's the case why not `ParseRequestURI` there and save into `c`?

---

_[cmd/statspusher/config_test.go, line 121 [r5]](https://reviewable.io:443/reviews/cerana/cerana/238#-KKypxfYCDPYk43WiCkN:-KKypxfYCDPYk43WiCkO:-15118860) ([raw file](https://github.com/cerana/cerana/blob/876960bf030272ac9949c6e5d0ab1e8cbf3dcdaf/cmd/statspusher/config_test.go#L121)):_

> ``` Go
>       {"invalud nodeDataURL", "asdf", u, 5, 4, 3, 2, "invalid nodeDataURL"},
>       {"missing clusterDataURL", u, "", 5, 4, 3, 2, "missing clusterDataURL"},
>       {"invalud clusterDataURL", u, "asdf", 5, 4, 3, 2, "invalid clusterDataURL"},
> ```

can be squashed into where this was introduced... just saying ;)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/238)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[cmd/statspusher/config.go, line 66 [r2]](https://reviewable.io:443/reviews/cerana/cerana/238#-KKyPrduK92BHfaE1B8w:-KKz0y5Ll45eXIONhUZG:1571362117) ([raw file](https://github.com/cerana/cerana/blob/a53c68702cac9e6b2c6e9ec3a1b82dcd8e333fa0/cmd/statspusher/config.go#L66)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> can use `flagSet.Duration`. Is there a card for updating all cli duration args to time.Duration?
> </details>
> Done. Converted it to `Duration` and updated all related tests. Uses units in the value. I don't think there's an issue yet for converting the others.

---

_[cmd/statspusher/config.go, line 178 [r2]](https://reviewable.io:443/reviews/cerana/cerana/238#-KKyQ6B0Oee9njeWT9SH:-KKz-btfT-CRZpUfbc1q:-485110604) ([raw file](https://github.com/cerana/cerana/blob/a53c68702cac9e6b2c6e9ec3a1b82dcd8e333fa0/cmd/statspusher/config.go#L178)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> should be `== 0` since uint64s will never be `< 0`
> </details>
> Sure.

---

_[cmd/statspusher/config.go, line 141 [r3]](https://reviewable.io:443/reviews/cerana/cerana/238#-KKypFhgil5K6wm5w9RR:-KKz4DfcJj-2CFyPixJW:855447544) ([raw file](https://github.com/cerana/cerana/blob/9f45ee3e4ac6a8e96634e67b8cc3259e0d43625c/cmd/statspusher/config.go#L141)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> if that's the case why not `ParseRequestURI` there and save into `c`?
> </details>
> I've been pondering an idea for this and other providers/coordinators of, at config load time, extracting everything from viper into a `ConfigData` instance and then saving that as `c.configData`. We can still keep a reference to viper around and eventually implement config watching, in which case it would validate the data and replace `c.configData` on change. That would eliminate things like repeated URL parsing.  In which case, I'd do that as a separate issue.

---

_[cmd/statspusher/config_test.go, line 121 [r5]](https://reviewable.io:443/reviews/cerana/cerana/238#-KKypxfYCDPYk43WiCkN:-KKz5NxYkSN7b-wVsmSx:770944328) ([raw file](https://github.com/cerana/cerana/blob/876960bf030272ac9949c6e5d0ab1e8cbf3dcdaf/cmd/statspusher/config_test.go#L121)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> can be squashed into where this was introduced... just saying ;)
> </details>
> NodeDataURL and ClusterDataURL came in two different commits.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/238)_

**Comment by mmlb** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[cmd/statspusher/config.go, line 141 [r3]](https://reviewable.io:443/reviews/cerana/cerana/238#-KKypFhgil5K6wm5w9RR:-KKz5xUnL-B6cMtlFSjE:-301274643) ([raw file](https://github.com/cerana/cerana/blob/9f45ee3e4ac6a8e96634e67b8cc3259e0d43625c/cmd/statspusher/config.go#L141)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> I've been pondering an idea for this and other providers/coordinators of, at config load time, extracting everything from viper into a `ConfigData` instance and then saving that as `c.configData`. We can still keep a reference to viper around and eventually implement config watching, in which case it would validate the data and replace `c.configData` on change. That would eliminate things like repeated URL parsing.  In which case, I'd do that as a separate issue.
> </details>
> sgtm, is there an issue?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/238)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[cmd/statspusher/config.go, line 141 [r3]](https://reviewable.io:443/reviews/cerana/cerana/238#-KKypFhgil5K6wm5w9RR:-KL1omiXdjbyEDdb3RZX:-1219332863) ([raw file](https://github.com/cerana/cerana/blob/9f45ee3e4ac6a8e96634e67b8cc3259e0d43625c/cmd/statspusher/config.go#L141)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> sgtm, is there an issue?
> </details>
> yup #243 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/238)_

**Pull request merged**
