### PR TITLE
Change how heartbeats are stored

### LINKED ISSUE #257: Heartbeat Directory Structure
#### Issue Description

In order to track datasets and bundles beyond what is known by the `clusterconf-provider`, move heartbeats out from under config entries and into a new `heartbeat` directory. This will allow heartbeats of all datasets and bundles, giving the cluster tick process a better idea of what to destroy.
- /heartbeats
  - /bundles
    - /{id} (ephemeral directory)
      - “serial”: “ip” (TTL Record)
  - /datasets
    - /{id} (ephemeral directory)
      - “ip”: boolean indicating if in use (TTL Record)

### PR DESCRIPTION
**Pull request by bbickerton**
#### Description:

Break dataset and bundle heartbeats out to their own prefix.
Store heartbeats for all local datasets (in a specified dir) and bundles regardless of whether they are configured in clusterconf.
Determine whether datasets are in use by a bundle currently in use on the node (via bundle heartbeats) when setting a dataset heartbeat.
#### Issues affected:

Resolves #257

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/266)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 5 of 5 files at r1, 5 of 5 files at r2, 6 of 6 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, 4 of 4 files at r8, 6 of 6 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[cmd/statspusher/dataset.go, line 31 [r8]](https://reviewable.io:443/reviews/cerana/cerana/266#-KMaEozmtm3iCDroMZis:-KMaEozmtm3iCDroMZit:-2115611367) ([raw file](https://github.com/cerana/cerana/blob/5438cb76a80cdda451c948f8cc5fd3ed1276d352/cmd/statspusher/dataset.go#L31)):_

> ``` Go
>   requests := map[string]struct {
>       task     string
>       url      *url.URL
> ```

this doesn't change and so can be extracted

---

_[cmd/statspusher/dataset.go, line 73 [r8]](https://reviewable.io:443/reviews/cerana/cerana/266#-KMaFKu-Vm7U2-GeLdB1:-KMaFKu0kqqBKEchKDhE:868029392) ([raw file](https://github.com/cerana/cerana/blob/5438cb76a80cdda451c948f8cc5fd3ed1276d352/cmd/statspusher/dataset.go#L73)):_

> ``` Go
>   // also determine whether they are in use based on bundle heartbeat and conf
>   datasets := make([]clusterconf.DatasetHeartbeatArgs, 0, len(listResult))
>   for _, dataset := range listResult {
> ```

omg so many loops. Would it make sense to convert some of these things into maps so that we can take advantage of maps' constant time lookup?

---

_[providers/clusterconf/dataset.go, line 163 [r2]](https://reviewable.io:443/reviews/cerana/cerana/266#-KM_yXQau7UmHrDrxy1C:-KM_yXQbnv2p0Ova4pxA:654910879) ([raw file](https://github.com/cerana/cerana/blob/c16a0a876d54b3d465ef81337b0f56ffb5d2872a/providers/clusterconf/dataset.go#L163)):_

> ``` Go
>   var err error
>   key := path.Join(datasetsPrefix, d.ID, "config")
>   value, err := d.c.kvGet(key) // Blocking
> ```

hmmm whats the point of this comment?

---

_[providers/clusterconf/heartbeat.go, line 132 [r3]](https://reviewable.io:443/reviews/cerana/cerana/266#-KMaBf35_cq_14vBWohf:-KMaBf35_cq_14vBWohg:-2003289092) ([raw file](https://github.com/cerana/cerana/blob/ff77c6aff926e4e4bcf7b65688cba111468c0e05/providers/clusterconf/heartbeat.go#L132)):_

> ``` Go
> 
> // MarshalJSON marshals BundleHeartbeatList into a JSON map, converting uint
> // keys to strings.
> ```

TODO: until go 1.7 comes out.

---

_[providers/clusterconf/heartbeat.go, line 149 [r3]](https://reviewable.io:443/reviews/cerana/cerana/266#-KMaBfqBpREuOsvR0u7a:-KMaBfqBpREuOsvR0u7b:-2003289092) ([raw file](https://github.com/cerana/cerana/blob/ff77c6aff926e4e4bcf7b65688cba111468c0e05/providers/clusterconf/heartbeat.go#L149)):_

> ``` Go
> 
> // UnmarshalJSON unmarshals JSON into a BundleHeartbeatList, converting string
> // keys to uints.
> ```

TODO: until go 1.7 comes out.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/266)_

**Comment by bbickerton** [comment]
Review status: 14 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

_[cmd/statspusher/dataset.go, line 31 [r8]](https://reviewable.io:443/reviews/cerana/cerana/266#-KMaEozmtm3iCDroMZis:-KMe5JmgUz6WOBN29Fnl:-1125520848) ([raw file](https://github.com/cerana/cerana/blob/5438cb76a80cdda451c948f8cc5fd3ed1276d352/cmd/statspusher/dataset.go#L31)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> this doesn't change and so can be extracted
> </details>
> True. It was necessary before, but no longer. 

---

_[cmd/statspusher/dataset.go, line 73 [r8]](https://reviewable.io:443/reviews/cerana/cerana/266#-KMaFKu-Vm7U2-GeLdB1:-KMe66gzEi9HscSNiZDG:-203803057) ([raw file](https://github.com/cerana/cerana/blob/5438cb76a80cdda451c948f8cc5fd3ed1276d352/cmd/statspusher/dataset.go#L73)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> omg so many loops. Would it make sense to convert some of these things into maps so that we can take advantage of maps' constant time lookup?
> </details>
> The joys of heirarchical kv instead of relational. Created an in-use map for datasets on the current node before cycling through the local datasets.

---

_[providers/clusterconf/dataset.go, line 163 [r2]](https://reviewable.io:443/reviews/cerana/cerana/266#-KM_yXQau7UmHrDrxy1C:-KMe4x7nIUtZ1LMiahjf:855598400) ([raw file](https://github.com/cerana/cerana/blob/c16a0a876d54b3d465ef81337b0f56ffb5d2872a/providers/clusterconf/dataset.go#L163)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> hmmm whats the point of this comment?
> </details>
> Leftover from development I think. Removed.

---

_[providers/clusterconf/heartbeat.go, line 132 [r3]](https://reviewable.io:443/reviews/cerana/cerana/266#-KMaBf35_cq_14vBWohf:-KMe4bEAtmwEUQRUxbBz:-499146009) ([raw file](https://github.com/cerana/cerana/blob/ff77c6aff926e4e4bcf7b65688cba111468c0e05/providers/clusterconf/heartbeat.go#L132)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> TODO: until go 1.7 comes out.
> </details>
> Done.

---

_[providers/clusterconf/heartbeat.go, line 149 [r3]](https://reviewable.io:443/reviews/cerana/cerana/266#-KMaBfqBpREuOsvR0u7a:-KMe4arblRBPJ-06XAvy:-499146009) ([raw file](https://github.com/cerana/cerana/blob/ff77c6aff926e4e4bcf7b65688cba111468c0e05/providers/clusterconf/heartbeat.go#L149)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> TODO: until go 1.7 comes out.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/266)_

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r10, 1 of 1 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/clusterconf/bundle.go, line 340 [r12]](https://reviewable.io:443/reviews/cerana/cerana/266#-KMex-hjuXhuysYIdiTI:-KMex-hjuXhuysYIdiTJ:-1378056395) ([raw file](https://github.com/cerana/cerana/blob/8ad69cdaacf634ad031f3aeeb6c6c45e0a6fe4e4/providers/clusterconf/bundle.go#L340)):_

> ``` Go
>   var err error
>   key := path.Join(bundlesPrefix, strconv.FormatUint(b.ID, 10), "config")
>   value, err := b.c.kvGet(key) // Blocking
> ```

sorry, I missed this blocking earlier

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/266)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[providers/clusterconf/bundle.go, line 340 [r12]](https://reviewable.io:443/reviews/cerana/cerana/266#-KMex-hjuXhuysYIdiTI:-KMexadUVbrKHThu_xXP:-469593337) ([raw file](https://github.com/cerana/cerana/blob/8ad69cdaacf634ad031f3aeeb6c6c45e0a6fe4e4/providers/clusterconf/bundle.go#L340)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> sorry, I missed this blocking earlier
> </details>
> done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/266)_

**Comment by mmlb** [comment]
Reviewed 1 of 2 files at r16, 3 of 3 files at r19, 2 of 4 files at r20, 5 of 6 files at r21, 2 of 2 files at r22, 1 of 2 files at r23, 1 of 1 files at r24.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/266)_

**Pull request merged**
