### PR TITLE
Wrap zfs and zfs/nv errors with the errors package

### PR DESCRIPTION
**Pull request by bbickerton**
#### Description:

Wrap zfs and zfs/nv errors with the errors package for that stacktrace and context goodness.
#### Issues affected:

Related #308

---

This change is [Reviewable](https://reviewable.io/reviews/cerana/cerana/319)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[zfs/create.go, line 23 [r1]](https://reviewable.io:443/reviews/cerana/cerana/319#-KOovn2Dy4Dt7z1RUKTn:-KOovn2EHIShFHqGA4hm:btwl7wy) ([raw file](https://github.com/cerana/cerana/blob/e04debf19d4f4e554aacac6751d8c0836c395ca0/zfs/create.go#L23)):_

> ``` Go
>   err := nv.NewNativeEncoder(encoded).Encode(m)
>   if err != nil {
>       return errors.Wrapv(err, map[string]interface{}{"name": name, "input": m})
> ```

I think args would make a better key...

---

_[zfs/nv/decode.go, line 25 [r1]](https://reviewable.io:443/reviews/cerana/cerana/319#-KOowXWZ6xSw9fu_JV6Y:-KOowXWZ6xSw9fu_JV6Z:bny9l5f) ([raw file](https://github.com/cerana/cerana/blob/e04debf19d4f4e554aacac6751d8c0836c395ca0/zfs/nv/decode.go#L25)):_

> ``` Go
>       err = errors.Newv("invalid encoding", map[string]interface{}{"encoding": enc.Encoding})
>   } else if enc.Endianess > maxEndian {
>       err = errors.Newv("invalid endianess", map[string]interface{}{"endianess": enc.Endianess})
> ```

mis-spelling, its endianness

---

_[zfs/nv/native_decoder.go, line 98 [r1]](https://reviewable.io:443/reviews/cerana/cerana/319#-KOp-XOy-fqMh3nCExRr:-KOp-XOy-fqMh3nCExRs:b-pomn5k) ([raw file](https://github.com/cerana/cerana/blob/e04debf19d4f4e554aacac6751d8c0836c395ca0/zfs/nv/native_decoder.go#L98)):_

> ``` Go
>   err := binary.Read(d.r, binary.LittleEndian, &d.pair.nativeMeta)
>   if err != nil {
>       return "", 0, errors.Wrap(err, "failed to decode meta")
> ```

nvpair metadata

---

_[zfs/nv/native_decoder.go, line 104 [r1]](https://reviewable.io:443/reviews/cerana/cerana/319#-KOp-YtT7GS6LQ38fmCc:-KOp-YtT7GS6LQ38fmCd:b-pomn5k) ([raw file](https://github.com/cerana/cerana/blob/e04debf19d4f4e554aacac6751d8c0836c395ca0/zfs/nv/native_decoder.go#L104)):_

> ``` Go
>   buf := make([]byte, len)
>   if _, err = d.r.Read(buf); err != nil {
>       return "", 0, errors.Wrap(err, "failed to read meta buffer")
> ```

nvpair metadata

---

_[zfs/nv/xdr_decoder.go, line 60 [r1]](https://reviewable.io:443/reviews/cerana/cerana/319#-KOp1lVTD-G8WzZfQAEe:-KOp1lVTD-G8WzZfQAEf:b-pomn5k) ([raw file](https://github.com/cerana/cerana/blob/e04debf19d4f4e554aacac6751d8c0836c395ca0/zfs/nv/xdr_decoder.go#L60)):_

> ``` Go
> func (d *XDRDecoder) meta() (string, dataType, error) {
>   _, err := xdr.Unmarshal(d.r, &d.pair)
>   return d.pair.Name, d.pair.Type, errors.Wrap(err, "failed to decode meta")
> ```

nvpair metadata

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/319)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[zfs/create.go, line 23 [r1]](https://reviewable.io:443/reviews/cerana/cerana/319#-KOovn2Dy4Dt7z1RUKTn:-KOp4YNzliqVwMzk0_oZ:b5v64bs) ([raw file](https://github.com/cerana/cerana/blob/e04debf19d4f4e554aacac6751d8c0836c395ca0/zfs/create.go#L23)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> I think args would make a better key...
> </details>
> I went with "input" because that's what it's called in `ioctl()` and wanted to make for consistent error contextual data naming. I guess I could change the error data key inside `ioctl()` to be "args"...

---

_[zfs/nv/decode.go, line 25 [r1]](https://reviewable.io:443/reviews/cerana/cerana/319#-KOowXWZ6xSw9fu_JV6Y:-KOp51UPZLl19-s1TZro:bbtuia9) ([raw file](https://github.com/cerana/cerana/blob/e04debf19d4f4e554aacac6751d8c0836c395ca0/zfs/nv/decode.go#L25)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> mis-spelling, its endianness
> </details>
> It was one "n" in both `enc.Endianess` and the error message before this change. Fixed the error message; i'll leave the `encoding{}` field change for another pr.

---

_[zfs/nv/native_decoder.go, line 98 [r1]](https://reviewable.io:443/reviews/cerana/cerana/319#-KOp-XOy-fqMh3nCExRr:-KOp5eQHHrz0Epd4YkGK:b-896fix) ([raw file](https://github.com/cerana/cerana/blob/e04debf19d4f4e554aacac6751d8c0836c395ca0/zfs/nv/native_decoder.go#L98)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> nvpair metadata
> </details>
> Done.

---

_[zfs/nv/native_decoder.go, line 104 [r1]](https://reviewable.io:443/reviews/cerana/cerana/319#-KOp-YtT7GS6LQ38fmCc:-KOp5epDBJkgGXbwuDoB:b-896fix) ([raw file](https://github.com/cerana/cerana/blob/e04debf19d4f4e554aacac6751d8c0836c395ca0/zfs/nv/native_decoder.go#L104)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> nvpair metadata
> </details>
> Done.

---

_[zfs/nv/xdr_decoder.go, line 60 [r1]](https://reviewable.io:443/reviews/cerana/cerana/319#-KOp1lVTD-G8WzZfQAEe:-KOp5pyc5RfJHSMSvcOy:b-896fix) ([raw file](https://github.com/cerana/cerana/blob/e04debf19d4f4e554aacac6751d8c0836c395ca0/zfs/nv/xdr_decoder.go#L60)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> nvpair metadata
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/319)_

**Comment by mmlb** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[zfs/create.go, line 23 [r1]](https://reviewable.io:443/reviews/cerana/cerana/319#-KOovn2Dy4Dt7z1RUKTn:-KOzxSCNz9jBLqUmtVMc:b-ske7iu) ([raw file](https://github.com/cerana/cerana/blob/e04debf19d4f4e554aacac6751d8c0836c395ca0/zfs/create.go#L23)):_
<details><summary>

<i>Previously, TauZero (Brian Bickerton) wrote…</i></summary>



> I went with "input" because that's what it's called in `ioctl()` and wanted to make for consistent error contextual data naming. I guess I could change the error data key inside `ioctl()` to be "args"...
> </details>
> +1 for args along with the ioctl change

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/319)_

**Comment by bbickerton** [comment]
Review status: 15 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

_[zfs/create.go, line 23 [r1]](https://reviewable.io:443/reviews/cerana/cerana/319#-KOovn2Dy4Dt7z1RUKTn:-KOzyB-Qo2ZKsLgWdfMd:b-896fix) ([raw file](https://github.com/cerana/cerana/blob/e04debf19d4f4e554aacac6751d8c0836c395ca0/zfs/create.go#L23)):_
<details><summary>

<i>Previously, mmlb (Manuel Mendez) wrote…</i></summary>



> +1 for args along with the ioctl change
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/319)_

**Comment by mmlb** [comment]
Reviewed 11 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cerana/cerana/319)_

**Pull request merged**
